### ISSUE TITLE
Modelgen is broken 

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-distro#1075]
On the current snapshot (master/3.0.0 branch), the Model Generation is broken. When doing that through the Setup Tasks, it dumps

```
Bundle org.eclipse.oomph.setup.workingsets 1.12.0.v20200203-0955, build=4528, branch=cd9ae2e25fc2c3563c893353f3385183bf12a782
Performing Launch ModelGen
Execute Debug Command
java.lang.NullPointerException
  at org.eclipse.jdt.launching.AbstractJavaLaunchConfigurationDelegate.getBootpathExt(AbstractJavaLaunchConfigurationDelegate.java:367)
  at org.eclipse.jdt.launching.AbstractJavaLaunchConfigurationDelegate.getVMSpecificAttributesMap(AbstractJavaLaunchConfigurationDelegate.java:677)
  at org.eclipse.jdt.launching.JavaLaunchDelegate.getVMRunnerConfiguration(JavaLaunchDelegate.java:92)
  at org.eclipse.jdt.launching.JavaLaunchDelegate.launch(JavaLaunchDelegate.java:153)
  at org.eclipse.m2e.internal.launch.MavenLaunchDelegate.launch(MavenLaunchDelegate.java:99)
  at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:860)
  at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:719)
  at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:714)
  at org.eclipse.oomph.setup.launching.impl.LaunchTaskImpl.perform(LaunchTaskImpl.java:272)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3827)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:3770)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5136)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2317)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5130)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:5128)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3761)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3736)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3629)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:585)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:711)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

The work-around to get the IDE going is running mvn from the command-line

**Comment by kgoderis** [comment]
[On Hold] / doing further tests/checks

**Comment by wang70880** [comment]
Do you know what the reason is behind? Why doesn't the official tutorial work?

**Comment by kaikreuzer** [comment]
I haven't seen this happening on any recent IDE setup, so I assume this is solved.
