### ISSUE TITLE
/chart yields a 500 NoClassDefFound error

### ISSUE THREAD

**Issue by xsnrg** [openhab/openhab-distro#118]
Feb 1 build, trying to get to /chart yields the follow exception. 

```
Problem accessing /chart. Reason:

    Server Error

Caused by:

java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11GraphicsEnvironment
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
	at org.eclipse.smarthome.ui.internal.chart.DefaultChartProvider.createChart(DefaultChartProvider.java:221)
	at org.eclipse.smarthome.ui.internal.chart.ChartServlet.doGet(ChartServlet.java:190)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:271)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by kaikreuzer** [comment]
This is nasty - the class GraphicsEnvironment does a Class.forName specific on the platform it is running on and it uses a class from sun.awt on X11 based systems. I hope that https://github.com/eclipse/smarthome/pull/979 resolves the issue.

**Comment by kaikreuzer** [comment]
After some further analysis, I think we have to set `-Djava.awt.headless=true` in our distro (that used to be the case in the non-karaf distro already), see also http://stackoverflow.com/questions/1687898/java-lang-noclassdeffounderror-sun-awt-x11graphicsenvironment-issuses-faced-whi/1688269#1688269.

**Comment by maggu2810** [comment]
Okay. But at least I would like to get this exception, too. :wink: 
@xsnrg could you read https://github.com/eclipse/smarthome/pull/979#issuecomment-179730291 and give me instructions what can I do to reproduce this exception?

**Comment by xsnrg** [comment]
I can reproduce this only on one system so far.  The system is running 64 bit Fedora 23 on an Intel NUC.  I have pulled down the latest bundle on a Pi2, and it is working there.  I have also pulled down the latest bundle on another Fedora 23 box, and it is working there as well.  At this point I need to updated the NUC and see if the problem is still there.  I will report back.

**Comment by xsnrg** [comment]
After updating to Feb 4 build, the problem is no longer there and charts are working again.  Will chalk this up to a bad build/flaky download/ flaky startup or sunspots (though I restarted a few times).

**Comment by kaikreuzer** [comment]
I would still think that `-Djava.awt.headless=true` would make a lot of sense.
@dvanherbergen, @maggu2810, would you agree?

**Comment by maggu2810** [comment]
1. I assume it makes sense
2. Perhaps its related to boot-delegation

**Comment by dvanherbergen** [comment]
I don't think it will harm anything to set that property...

**Comment by xsnrg** [comment]
I started having this problem again with today's build.  I guess I should not have closed this yet.

I added the headless option to the default java opts in the karaf file, but it did not seem to get picked up, so I will have to find which options get used and will report back.

    DEFAULT_JAVA_OPTS="-Xms$JAVA_MIN_MEM -Xmx$JAVA_MAX_MEM -XX:+UnlockDiagnosticVMOptions -XX:+UnsyncloadClass -Djava.awt.headless=true"

**Comment by xsnrg** [comment]
I added it to setenv in runtime/karaf/bin and it picked it up.  More importantly, /charts works correctly again.

EXTRA_JAVA_OPTS_COMMON="-Xmx256m -Djava.awt.headless=true"

**Comment by thopiekar** [comment]
This bug is back on 3.3M2 and probably earlier.
Happens on my Synology NAS, which is headless of course.
