### ISSUE TITLE
manual installation: failed to save history

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-distro#1195]
Following the manual installation instructions for linux systems an user without any home directory should be created.
I named the user "openhab" (as I used openHAB 3 instead of openHAB 2 I don't want to follow the instruction suggestion to use openhab2 ).

After starting the distribution (3.0.0.M4) this warning is shown in the log:

```
17:12:16.707 [WARN ] [org.jline                            ] - Failed to save history
java.nio.file.AccessDeniedException: /home/openhab
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]
	at java.nio.file.Files.createDirectory(Files.java:689) ~[?:?]
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:796) ~[?:?]
	at java.nio.file.Files.createDirectories(Files.java:782) ~[?:?]
	at org.jline.reader.impl.history.DefaultHistory.internalWrite(DefaultHistory.java:229) ~[bundleFile:?]
	at org.jline.reader.impl.history.DefaultHistory.save(DefaultHistory.java:223) ~[bundleFile:?]
	at org.jline.reader.impl.history.DefaultHistory.add(DefaultHistory.java:375) [bundleFile:?]
	at org.jline.reader.impl.LineReaderImpl.finishBuffer(LineReaderImpl.java:1026) [bundleFile:?]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:612) [bundleFile:?]
	at org.apache.karaf.shell.impl.console.ConsoleSessionImpl.readCommand(ConsoleSessionImpl.java:444) [bundleFile:4.2.7]
	at org.apache.karaf.shell.impl.console.ConsoleSessionImpl.run(ConsoleSessionImpl.java:402) [bundleFile:4.2.7]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

I see that this has been caused by jline, so not by an openHAB bundle, but as it has been raised by the openHAB distribution, you should perhaps care about.

**Comment by mlommers** [comment]
upgraded from 2.5.12 to 3.0.2 and seeing once in a while the exact same issue as above. Any idea on the cause and what can be done?
