### ISSUE TITLE
Can't install bindings / addons right now on Openhab Snapshot build #2050

### ISSUE THREAD

**Issue by LukasA83** [openhab/openhab-distro#1209]
After upgrade to latest snapshot docker image of Openhab 3 I get following error (seems openhab.jfrog.io is down (502)):
`2020-12-09 16:40:21.884 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-tr064, openhab-persistence-mapdb, openhab-binding-exec, openhab-binding-deconz, openhab-persistence-influxdb, openhab-ui-habpanel, openhab-binding-daikin, openhab-binding-mqtt, openhab-transformation-map, openhab-binding-logreader, openhab-binding-smartmeter, openhab-binding-telegram, openhab-transformation-xslt, openhab-transformation-exec, openhab-transformation-scale, openhab-binding-lcn, openhab-binding-mail, openhab-transformation-javascript, openhab-transformation-regex, openhab-transformation-jsonpath, openhab-transformation-xpath, openhab-binding-hpprinter, openhab-ui-basic, openhab-binding-openweathermap, openhab-binding-astro': Error:
	Error downloading mvn:org.openhab.addons.bundles/org.openhab.binding.tr064/3.0.0-SNAPSHOT`
and 

`
org.apache.karaf.features.internal.util.MultiException: Error:
	Error downloading mvn:org.openhab.addons.bundles/org.openhab.binding.tr064/3.0.0-SNAPSHOT

	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.<init>(MavenDownloadManager.java:91)

	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager.createDownloader(MavenDownloadManager.java:72)

	at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:457)

	at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:452)

	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:224)

	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:393)

	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)

	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)

	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

	at java.base/java.lang.Thread.run(Thread.java:834)

	Suppressed: java.io.IOException: Error downloading mvn:org.openhab.addons.bundles/org.openhab.binding.tr064/3.0.0-SNAPSHOT

		at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:77)

		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)

		... 3 more

	Caused by: java.io.IOException: Error resolving artifact org.openhab.addons.bundles:org.openhab.binding.tr064:jar:3.0.0-SNAPSHOT: [Could not transfer artifact org.openhab.addons.bundles:org.openhab.binding.tr064:jar:3.0.0-SNAPSHOT from/to openhab (https://openhab.jfrog.io/openhab/libs-snapshot/): Failed to transfer file https://openhab.jfrog.io/openhab/libs-snapshot/org/openhab/addons/bundles/org.openhab.binding.tr064/3.0.0-SNAPSHOT/org.openhab.binding.tr064-3.0.0-SNAPSHOT.jar with status code 502]

		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.configureIOException(AetherBasedResolver.java:803)

		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:774)

		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:657)

		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:598)

		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:565)

		at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:52)

		at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)

		... 6 more

		Suppressed: shaded.org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.openhab.addons.bundles:org.openhab.binding.tr064:jar:3.0.0-SNAPSHOT from/to openhab (https://openhab.jfrog.io/openhab/libs-snapshot/): Failed to transfer file https://openhab.jfrog.io/openhab/libs-snapshot/org/openhab/addons/bundles/org.openhab.binding.tr064/3.0.0-SNAPSHOT/org.openhab.binding.tr064-3.0.0-SNAPSHOT.jar with status code 502

			at shaded.org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52)

			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:368)

			at shaded.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)

			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:642)

			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)

			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:489)

			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:390)

			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)

			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)

			at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)

			at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)

			... 11 more

		Caused by: shaded.org.apache.maven.wagon.TransferFailedException: Failed to transfer file https://openhab.jfrog.io/openhab/libs-snapshot/org/openhab/addons/bundles/org.openhab.binding.tr064/3.0.0-SNAPSHOT/org.openhab.binding.tr064-3.0.0-SNAPSHOT.jar with status code 502

			at shaded.org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1139)

			at shaded.org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1072)

			at shaded.org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:126)

			at shaded.org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)

			at shaded.org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)

			at shaded.org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:567)

			at shaded.org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:435)

			at shaded.org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:412)

			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:456)

			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:363)

			... 20 more

	Caused by: shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact org.openhab.addons.bundles:org.openhab.binding.tr064:jar:3.0.0-SNAPSHOT

		at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:413)

		at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)

		at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)

		at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)

		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)

		... 11 more`

**Comment by J-N-K** [comment]
Jfrog has problems. This is not related to openHAB

**Comment by LukasA83** [comment]
Thanks for prompt response, I'll keep an eye on the status of Jfrog...
