### ISSUE TITLE
org.apache.felix.configadmin: Unexpected problem updating configuration org.eclipse.smarthome.folder

### ISSUE THREAD

**Issue by msfunty** [openhab/openhab-distro#124]
In the most current version of OH2 (online) there is an entry in log file:

`2016-02-09 20:12:46.607 [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.cm.ManagedService, id=289, bundle=107/mvn:org.eclipse.smarthome.model/org.eclipse.smarthome.model.core/0.8.0-SNAPSHOT]: Unexpected problem updating configuration org.eclipse.smarthome.folder
java.lang.NullPointerException
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.createItemFromModelItem(GenericItemProvider.java:206)[108:org.eclipse.smarthome.model.item:0.8.0.201601301304]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.processBindingConfigsFromModel(GenericItemProvider.java:166)[108:org.eclipse.smarthome.model.item:0.8.0.201601301304]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:396)[108:org.eclipse.smarthome.model.item:0.8.0.201601301304]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:200)[107:org.eclipse.smarthome.model.core:0.8.0.201601301304]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:97)[107:org.eclipse.smarthome.model.core:0.8.0.201601301304]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:240)[107:org.eclipse.smarthome.model.core:0.8.0.201601301304]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.notifyUpdateToModelRepo(FolderObserver.java:169)[107:org.eclipse.smarthome.model.core:0.8.0.201601301304]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.updated(FolderObserver.java:150)[107:org.eclipse.smarthome.model.core:0.8.0.201601301304]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1444)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1400)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:143)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:110)[7:org.apache.felix.configadmin:1.8.8]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_71]
`

I don't know if there is actually any misfunctionality. It doesn't seem so...

**Comment by kaikreuzer** [comment]
Thanks, this looks like a bug that only occurs on certain startup order situations - it should hopefully be fixed through https://github.com/eclipse/smarthome/pull/1027.
