### ISSUE TITLE
start.bat not running

### ISSUE THREAD

**Issue by hazaart** [openhab/openhab-distro#1248]
Clean windows install of V3.0.0. Java V jdk-11.0.9

Exception when fist run:
```
 org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-runtime-ui; type=karaf.feature; version="[3.0.0,3.0.0]"; filter:="(&(osgi.identity=openhab-runtime-ui)(type=karaf.feature)(version>=3.0.0)(version<=3.0.0))" [caused by: Unable to resolve openhab-runtime-ui/3.0.0: missing requirement [openhab-runtime-ui/3.0.0] osgi.identity; osgi.identity=openhab-core-ui; type=karaf.feature [caused by: Unable to resolve openhab-core-ui/3.0.0: missing requirement [openhab-core-ui/3.0.0] osgi.identity; osgi.identity=openhab-core-base; type=karaf.feature [caused by: Unable to resolve openhab-core-base/3.0.0: missing requirement [openhab-core-base/3.0.0] osgi.identity; osgi.identity=org.openhab.core.automation; type=osgi.bundle; version="[3.0.0,3.0.0]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.core.automation/3.0.0: missing requirement [org.openhab.core.automation/3.0.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.openhab.core)(version>=3.0.0)(!(version>=4.0.0)))" [caused by: Unable to resolve org.openhab.core/3.0.0: missing requirement [org.openhab.core/3.0.0] osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"]]]]]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
        at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:392)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:378)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:332)
        at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:257)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:393)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve openhab-runtime-ui/3.0.0: missing requirement [openhab-runtime-ui/3.0.0] osgi.identity; osgi.identity=openhab-core-ui; type=karaf.feature [caused by: Unable to resolve openhab-core-ui/3.0.0: missing requirement [openhab-core-ui/3.0.0] osgi.identity; osgi.identity=openhab-core-base; type=karaf.feature [caused by: Unable to resolve openhab-core-base/3.0.0: missing requirement [openhab-core-base/3.0.0] osgi.identity; osgi.identity=org.openhab.core.automation; type=osgi.bundle; version="[3.0.0,3.0.0]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.core.automation/3.0.0: missing requirement [org.openhab.core.automation/3.0.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.openhab.core)(version>=3.0.0)(!(version>=4.0.0)))" [caused by: Unable to resolve org.openhab.core/3.0.0: missing requirement [org.openhab.core/3.0.0] osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"]]]]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
        ... 12 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve openhab-core-ui/3.0.0: missing requirement [openhab-core-ui/3.0.0] osgi.identity; osgi.identity=openhab-core-base; type=karaf.feature [caused by: Unable to resolve openhab-core-base/3.0.0: missing requirement [openhab-core-base/3.0.0] osgi.identity; osgi.identity=org.openhab.core.automation; type=osgi.bundle; version="[3.0.0,3.0.0]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.core.automation/3.0.0: missing requirement [org.openhab.core.automation/3.0.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.openhab.core)(version>=3.0.0)(!(version>=4.0.0)))" [caused by: Unable to resolve org.openhab.core/3.0.0: missing requirement [org.openhab.core/3.0.0] osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"]]]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
        ... 13 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve openhab-core-base/3.0.0: missing requirement [openhab-core-base/3.0.0] osgi.identity; osgi.identity=org.openhab.core.automation; type=osgi.bundle; version="[3.0.0,3.0.0]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.core.automation/3.0.0: missing requirement [org.openhab.core.automation/3.0.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.openhab.core)(version>=3.0.0)(!(version>=4.0.0)))" [caused by: Unable to resolve org.openhab.core/3.0.0: missing requirement [org.openhab.core/3.0.0] osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"]]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
        ... 14 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve org.openhab.core.automation/3.0.0: missing requirement [org.openhab.core.automation/3.0.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.openhab.core)(version>=3.0.0)(!(version>=4.0.0)))" [caused by: Unable to resolve org.openhab.core/3.0.0: missing requirement [org.openhab.core/3.0.0] osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
        ... 15 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve org.openhab.core/3.0.0: missing requirement [org.openhab.core/3.0.0] osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
        ... 16 more
```

**Comment by kaikreuzer** [comment]
The important line is 
```
missing requirement [org.openhab.core/3.0.0] osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11)
```
It seems that openHAB isn't started with Java 11 (although you claim it is). Do you maybe have multiple java versions installed and JAVA_HOME points to a wrong one?

**Comment by hazaart** [comment]
Hi kaireuzer,

Yes I have 2 versions installed. Turns out the JAVA_HOME was not correctly set during installation of V11. I added it manually and it is now running.
Thanks!
