### ISSUE TITLE
Installation of binding fails

### ISSUE THREAD

**Issue by ccbur** [openhab/openhab-distro#1269]
## Summary
The docker images from https://hub.docker.com/r/openhab/openhab/ can no longer download bindings from openhab.jfrog.io.

See:
[Thread 1](https://community.openhab.org/t/openhab-2-5-12-downloading-of-mvn-mysql-mysql-connector-java-8-0-13-fails/118796)
[Thread 2](https://community.openhab.org/t/urgent-help-openhab-in-docker-container-fails-installing-bindings-but-internet-connection-works/118806/6
)
## Expected Behavior
Starting a docker image with a binding configured in addons.cfg should work.

## Current Behavior
The following exception is thrown:

```
org.apache.karaf.features.internal.util.MultiException: Error:
Error downloading mvn:mysql/mysql-connector-java/8.0.13
at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.(MavenDownloadManager.java:91)
at org.apache.karaf.features.internal.download.impl.MavenDownloadManager.createDownloader(MavenDownloadManager.java:72)
at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:457)
at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:452)
at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:224)
at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:393)
at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Suppressed: java.io.IOException: Error downloading mvn:mysql/mysql-connector-java/8.0.13
at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:77)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
… 3 more
Caused by: java.io.IOException: Error resolving artifact mysql:mysql-connector-java:jar:8.0.13: [Could not find artifact mysql:mysql-connector-java:jar:8.0.13 in openhab (https://openhab.jfrog.io/openhab/libs-release/)]
at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.configureIOException(AetherBasedResolver.java:803)
at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:774)
at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:657)
at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:598)
at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:565)
at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:52)
at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)
… 7 more
Suppressed: shaded.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact mysql:mysql-connector-java:jar:8.0.13 in openhab (https://openhab.jfrog.io/openhab/libs-release/)
at shaded.org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:368)
at shaded.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:642)
at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:489)
at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:390)
at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)
at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)
at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)
at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
… 12 more
Caused by: shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact mysql:mysql-connector-java:jar:8.0.13
at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:413)
at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)
at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)
at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)
at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
… 12 more
17:36:15.138 [ERROR] [core.karaf.internal.FeatureInstaller] [] - Failed installing ‘openhab-binding-http1, openhab-persistence-jdbc-mysql, openhab-transformation-javascript, openhab-persistence-influxdb, openhab-binding-novelanheatpump1, openhab-binding-weather1, openhab-misc-ruleengine, openhab-persistence-rrd4j, openhab-ui-basic, openhab-binding-onewire, openhab-binding-astro, openhab-binding-kostalinverter, openhab-binding-squeezebox, openhab-binding-knx, openhab-ui-paper’: Error:
Error downloading mvn:mysql/mysql-connector-java/8.0.13
```

## Possible Solution
Missing or wrong cert in keystore?

## Steps to Reproduce
1. Start openhab container
2. Install any binding

## Context
I can no longer use openHAB. Other users are effected, too.

## Your Environment
Docker container

### Image
*Images used:
openhab/openhab:2.5.5-debian
openhab/openhab:2.5.11-debian
openhab/openhab:2.5.12-debian
openhab/openhab:3.1.0-debian
*bindings: jdbc-mysql, but also every other binding

### Docker Host
* Operating System: self made Debian Buster
* Docker Version: 18.09.7
* Kernel Version: 4.14.2
* Architecture: armv7l

### Configuration
addons.cfg:
```
# The installation package of this openHAB instance
# Note: This is only regarded at the VERY FIRST START of openHAB
# Note: If you want to specify your add-ons yourself through entries below, set the package to "minimal"
# as otherwise your definition might be in conflict with what the installation package defines.
#
# Optional. If not set, the dashboard (https://<yourserver>:8080/) will ask you to choose a package.
#
# Valid options:
#   - minimal  : Installation only with dashboard, but no UIs or other add-ons. Use this for custom setups.
#   - simple   : Setup for using openHAB purely through UIs - you need to expect MANY constraints in functionality!
#   - standard : Default setup for normal users, best for textual setup
#   - expert   : Setup for expert users, especially for people migrating from openHAB 1.x
#   - demo     : A demo setup which includes UIs, a few bindings, config files etc.
#
# See https://www.openhab.org/docs/configuration/packages.html for a detailed explanation of these packages.
#
package = minimal

# Access Remote Add-on Repository
# Defines whether the remote openHAB add-on repository should be used for browsing and installing add-ons.
# This not only makes latest snapshots of add-ons available, it is also required for the installation of
# any legacy 1.x add-on. (default is true)
#
#remote = true

# Include legacy 1.x bindings. If set to true, it also allows the installation of 1.x bindings for which there is 
# already a 2.x version available (requires remote repo access, see above). (default is false)
#
#legacy = true

# A comma-separated list of bindings to install (e.g. "binding = sonos,knx,zwave")
#binding = astro,knx,novelanheatpump1,kostalinverter,onewire,squeezebox,weather1,http1
binding = astro,knx,novelanheatpump1,kostalinverter,onewire,weather1,http1

# A comma-separated list of UIs to install (e.g. "ui = basic,paper")
ui = basic,paper

# A comma-separated list of persistence services to install (e.g. "persistence = rrd4j,jpa")
persistence = rrd4j,jdbc-mysql,influxdb

# A comma-separated list of actions to install (e.g. "action = mail,pushover")
#action = 

# A comma-separated list of transformation services to install (e.g. "transformation = map,jsonpath")
transformation = javascript

# A comma-separated list of voice services to install (e.g. "voice = marytts,freetts")
#voice = 

# A comma-separated list of miscellaneous services to install (e.g. "misc = myopenhab")
misc = ruleengine
```

**Comment by ccbur** [comment]
I think I don't need to investigate a mitm attack as the certificate is always valid from a newer Ubuntu installation :-)

I guess the CDN might be a valid point I did not think about. Jfrog is using redirects to CloudFront, so I guess I'll never find out what the real url was :-(. But the last time I used CloudFront it had a caching default value of 24h, so I think I can rule this out for now as I've never seen anyone caching >36h. Or do you have any idea what Cache-Contol header is set at jfrog?

Today I tested the startup multiple times and it always worked always. Let's wait some more days and then I'll close this issue.

**Comment by ccbur** [comment]
No more errors after two weeks.

**Comment by majherek** [comment]
Hi, 

I do not want to start a new issue, but I have similar problem with my OH 2.5.12 instalation.

Today, due to some problems with astro binding, I clear cache manually. Stop my OH docker. Remove file from cache/* and tmp/* directories. In results I can't start OH normally. I get errors like this:
```
2021-05-28 15:11:45.997 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-exec, openhab-binding-airquality, openhab-action-satel, openhab-persistence-influxdb, openhab-ui-habpanel, openhab-action-pushover, openhab-binding-mqtt1, openhab-binding-chromecast, openhab-binding-mqtt, openhab-transformation-map, openhab-ui-classic, openhab-binding-ipcamera, openhab-binding-kodi, openhab-ui-habmin, openhab-transformation-xslt, openhab-action-mqtt, openhab-transformation-exec, openhab-ui-paper, openhab-transformation-scale, openhab-binding-samsungtv, openhab-binding-http1, openhab-binding-satel1, openhab-transformation-javascript, openhab-binding-sonos, openhab-transformation-regex, openhab-transformation-jsonpath, openhab-binding-mihome, openhab-transformation-xpath, openhab-ui-basic, openhab-action-mail, openhab-binding-ntp, openhab-binding-astro, openhab-binding-expire1': Error:

	Error downloading mvn:org.openhab.addons.bundles/org.openhab.transform.map/[2.5.0,2.6)
```
and in docker logs:
```
today at 15:12:45 org.apache.karaf.features.internal.util.MultiException: Error:
today at 15:12:45 	Error downloading mvn:org.openhab.addons.bundles/org.openhab.transform.map/[2.5.0,2.6)
today at 15:12:45 	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.<init>(MavenDownloadManager.java:91)
today at 15:12:45 	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager.createDownloader(MavenDownloadManager.java:72)
today at 15:12:45 	at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:457)
today at 15:12:45 	at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:452)
today at 15:12:45 	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:224)
today at 15:12:45 	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:393)
today at 15:12:45 	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
today at 15:12:45 	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
today at 15:12:45 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
today at 15:12:45 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
today at 15:12:45 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
today at 15:12:45 	at java.base/java.lang.Thread.run(Thread.java:829)
today at 15:12:45 	Suppressed: java.io.IOException: Error downloading mvn:org.openhab.addons.bundles/org.openhab.transform.map/[2.5.0,2.6)
today at 15:12:45 		at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:77)
today at 15:12:45 		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
today at 15:12:45 		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
today at 15:12:45 		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
today at 15:12:45 		... 3 more
today at 15:12:45 	Caused by: java.io.IOException: Error resolving artifact org.openhab.addons.bundles:org.openhab.transform.map:jar:[2.5.0,2.6): [Could not find metadata org.openhab.addons.bundles:org.openhab.transform.map/maven-metadata.xml in local (/openhab/userdata/tmp/mvn)]
today at 15:12:45 		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.configureIOException(AetherBasedResolver.java:803)
today at 15:12:45 		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:780)
today at 15:12:45 		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:657)
today at 15:12:45 		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:598)
today at 15:12:45 		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:565)
today at 15:12:45 		at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:52)
today at 15:12:45 		at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)
today at 15:12:45 		... 6 more
today at 15:12:45 		Suppressed: shaded.org.eclipse.aether.transfer.MetadataNotFoundException: Could not find metadata org.openhab.addons.bundles:org.openhab.transform.map/maven-metadata.xml in local (/openhab/userdata/tmp/mvn)
today at 15:12:45 			at shaded.org.eclipse.aether.internal.impl.DefaultMetadataResolver.resolve(DefaultMetadataResolver.java:220)
today at 15:12:45 			at shaded.org.eclipse.aether.internal.impl.DefaultMetadataResolver.resolveMetadata(DefaultMetadataResolver.java:178)
today at 15:12:45 			at shaded.org.apache.maven.repository.internal.DefaultVersionRangeResolver.getVersions(DefaultVersionRangeResolver.java:198)
today at 15:12:45 			at shaded.org.apache.maven.repository.internal.DefaultVersionRangeResolver.resolveVersionRange(DefaultVersionRangeResolver.java:148)
today at 15:12:45 			at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveVersionRange(DefaultRepositorySystem.java:232)
today at 15:12:45 			at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolveLatestVersionRange(AetherBasedResolver.java:1060)
today at 15:12:45 			at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:765)
today at 15:12:45 			... 11 more
today at 15:12:45 	Caused by: shaded.org.eclipse.aether.resolution.VersionRangeResolutionException: Error resolving artifact org.openhab.addons.bundles:org.openhab.transform.map:jar:[2.5.0,2.6)
today at 15:12:45 		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolveLatestVersionRange(AetherBasedResolver.java:1068)
today at 15:12:45 		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:765)
today at 15:12:45 		... 11 more
```
I use OH from docker (build by me with ffmpeg support to ipcameras binding). I build docker image today, after _git pull_ in openhab-docker directory.

I found also this today: https://community.openhab.org/t/openhab-3-0-2-patch-release-and-the-sunset-of-bintray/121231. 

And if I understand corectly, now OH try to download everything from _https://openhab.jfrog.io/_?
Is there any possibility to put *2.5.X* packages to _https://openhab.jfrog.io/_? If I search _org.openhab.transform.map_ there is only 3.X version.

https://openhab.jfrog.io/ui/packages/gav:%2F%2Forg.openhab.addons.bundles:org.openhab.transform.map?name=org.openhab.transform.map&type=packages

I download *openhab-addons-2.5.12.kar* from https://search.maven.org/artifact/org.openhab.distro/openhab-addons/2.5.12/kaf, but where should I put it or extract it in docker to succesfully run my OH 2.5.12 installation?

Please help @kaikreuzer.

**Comment by majherek** [comment]
I put the _openhab-addons-2.5.12.kar_ file to _addon_ folder and OH start working.
