### ISSUE TITLE
classic-ui doesn't start in offline distro

### ISSUE THREAD

**Issue by dvanherbergen** [openhab/openhab-distro#13]
The following exception is thrown:
```
2016-01-04 20:11:24.403 [ERROR] [org.eclipse.smarthome.ui.classic    ] - [org.eclipse.smarthome.classicui(176)] The activate method has thrown an exception
java.lang.IllegalStateException: Multiple servlets map to path: /classicui/app/*: org.ops4j.pax.web.service.spi.model.ServletModel-28,org.ops4j.pax.web.service.spi.model.ServletModel-31
	at org.eclipse.jetty.servlet.ServletHandler.updateMappings(ServletHandler.java:1488)
	at org.eclipse.jetty.servlet.ServletHandler.setServletMappings(ServletHandler.java:1585)
	at org.eclipse.jetty.servlet.ServletHandler.addServletMapping(ServletHandler.java:1023)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerImpl$2.call(JettyServerImpl.java:334)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerImpl$2.call(JettyServerImpl.java:329)
	at org.ops4j.pax.swissbox.core.ContextClassLoaderUtils.doWithClassLoader(ContextClassLoaderUtils.java:60)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerImpl.addServlet(JettyServerImpl.java:328)
	at org.ops4j.pax.web.service.jetty.internal.ServerControllerImpl$Started.addServlet(ServerControllerImpl.java:290)
	at org.ops4j.pax.web.service.jetty.internal.ServerControllerImpl.addServlet(ServerControllerImpl.java:110)
	at org.ops4j.pax.web.service.internal.HttpServiceStarted.registerServlet(HttpServiceStarted.java:211)
	at org.ops4j.pax.web.service.internal.HttpServiceStarted.registerServlet(HttpServiceStarted.java:190)
	at org.ops4j.pax.web.service.internal.HttpServiceStarted.registerServlet(HttpServiceStarted.java:175)
	at org.ops4j.pax.web.service.internal.HttpServiceProxy.registerServlet(HttpServiceProxy.java:64)
	at org.eclipse.smarthome.ui.classic.internal.servlet.WebAppServlet.activate(WebAppServlet.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_66]
```

**Comment by kaikreuzer** [comment]
I assumed that this was due to the whiteboard http service, which registers the servlet a second time. Should be solved by the upgrade of SHK, I hope.

**Comment by dvanherbergen** [comment]
I'm afraid not. My test was done with the new SHK and no whiteboard http service ...

**Comment by kaikreuzer** [comment]
:-(
Any idea what could then cause it?

**Comment by dvanherbergen** [comment]
Not yet. I'm having a look at implementing an ESH HttpContextService first. Maybe once we have a shared context, this problem will dissappear or at least be easier to track down.

**Comment by kaikreuzer** [comment]
So we should try to find out what is different to the Basic UI - because that works as expected.

**Comment by maggu2810** [comment]
Is immediate still set to true for that DS?
I see this error if deactivate is called and then activate again.
immediate=true solved this.

IIRC I see a bug entry for that somewhere.

2016-01-05 0:20 GMT+01:00 Kai Kreuzer <notifications@github.com>:

**Comment by maggu2810** [comment]
* https://ops4j1.jira.com/browse/PAXWEB-935
* https://ops4j1.jira.com/browse/PAXWEB-909
* https://ops4j1.jira.com/browse/PAXWEB-912

**Comment by kaikreuzer** [comment]
This makes me think that using a plain vanilla Jetty (as in the past) might have been a smoother solution... 

> Is immediate still set to true for that DS?

It is not for the Classic UI, but it is set for the Basic UI. So this might be indeed the difference.
So is this a workaround for https://ops4j1.jira.com/browse/PAXWEB-935?

**Comment by maggu2810** [comment]
It should be a workaround.
Hm, I have been sure, I have done the PR already...

**Comment by maggu2810** [comment]
That the one for the Basic UI: https://github.com/eclipse/smarthome/pull/699

**Comment by kaikreuzer** [comment]
> I have been sure, I have done the PR already...

Go and find it ;-)

Will you create one or shall I?

**Comment by maggu2810** [comment]
Please do so, as already stated I have not much time ATM.

**Comment by kaikreuzer** [comment]
No prob, done: https://github.com/eclipse/smarthome/pull/818

**Comment by kaikreuzer** [comment]
fixed in latest snapshot.
