### ISSUE TITLE
Failing finding rrd4j

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#1300]
Major issue with snapshot 2441 (first startup), apparently a problem to install rrd4j.
What is strange is that I am using the kar file which normally contains everything and so nothing should require a downlmoad.
```
org.apache.karaf.features.internal.util.MultiException: Error:
        Error downloading mvn:org.openhab.addons.bundles/org.openhab.persistence.rrd4j/3.1.0-SNAPSHOT
        at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.<init>(MavenDownloadManager.java:91)
        at org.apache.karaf.features.internal.download.impl.MavenDownloadManager.createDownloader(MavenDownloadManager.java:72)
        at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:457)
        at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:452)
        at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:224)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:399)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
        Suppressed: java.io.IOException: Error downloading mvn:org.openhab.addons.bundles/org.openhab.persistence.rrd4j/3.1.0-SNAPSHOT
                at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:77)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
                ... 3 more
        Caused by: java.io.IOException: Error resolving artifact org.openhab.addons.bundles:org.openhab.persistence.rrd4j:jar:3.1.0-SNAPSHOT: [Could not find artifact org.openhab.addons.bundles:org.openhab.persistence.rrd4j:jar:3.1.0-SNAPSHOT]
                at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.configureIOException(AetherBasedResolver.java:803)
                at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:774)
                at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:657)
                at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:598)
                at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:565)
                at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:52)
                at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)
                ... 6 more
                Suppressed: shaded.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.openhab.addons.bundles:org.openhab.persistence.rrd4j:jar:3.1.0-SNAPSHOT
                        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:403)
                        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)
                        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)
                        at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)
                        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
                        ... 11 more
        Caused by: shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact org.openhab.addons.bundles:org.openhab.persistence.rrd4j:jar:3.1.0-SNAPSHOT
                at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:413)
                at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)
                at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)
                at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)
                at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
                ... 11 more
```
@kaikreuzer : certainly something critical for the final 3.1.

**Comment by kaikreuzer** [comment]
I've analysed this and I don't think this is anything new.
It only happens if remote is set to false and the KAR file is used.
Seems to be a timing issue at startup - Karaf already tries to install the add-ons, while the KAR is still being processed/extracted. I have seen situations where it worked right away, in others, the exception above occurred.
On a second start, it should always work.

I don't think that's a regression and it is likely very complex to fix, so nothing to address for 3.1.

**Comment by lolodomo** [comment]
> I've analysed this and I don't think this is anything new.
> It only happens if remote is set to false and the KAR file is used.

Matching my setup.

> Seems to be a timing issue at startup - Karaf already tries to install the add-ons, while the KAR is still being processed/extracted. I have seen situations where it worked right away, in others, the exception above occurred.

First time I encountered this problem.

> On a second start, it should always work.

Trying...

**Comment by lolodomo** [comment]
At the third startup, it was finally OK.

**Comment by kaikreuzer** [comment]
Then you probably didn't wait long enough before shutting down 1st and 2nd startup.

**Comment by kaikreuzer** [comment]
I agree that it's not nice, but nothing where I see any quick and simple solution now.

**Comment by lolodomo** [comment]
I understand.

Is there already an iossue opened for that ? If one is already opened, I will close this one.

**Comment by lolodomo** [comment]
I am just surprised because I never encountered it.

**Comment by kaikreuzer** [comment]
No, I am not aware of any issue.

**Comment by kaikreuzer** [comment]
Just tested with 3.0.2 and didn't see this effect. Maybe a regression in the Karaf upgrade?
We can leave this issue open if you like, but I would give it a better description and title to make clear that this is about offline use case.

**Comment by wborn** [comment]
I often test my changes using local distro builds and then also sometimes run into such issues because the KAR files are not immediately installed. Then I just patiently wait for it to complete KAR installation.

To fix this properly the [FeatureInstaller](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java) would have to know that Karaf hasn't installed the KAR files yet, and postpone feature installation until it has finished doing so.

If that is not possible we could also add some configuration parameters to the `FeatureInstaller` so you can [delay (or speed up) the feature installation](https://github.com/openhab/openhab-core/blob/11a96d87d6441b6671eee417bcb7f0fd238b9df7/bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java#L165). When I don't use KAR files while testing, I often waste time while waiting for the FeaturesInstaller to install add-ons. :hourglass_flowing_sand:

**Comment by lolodomo** [comment]
> If that is not possible we could also add some configuration parameters to the `FeatureInstaller` so you can [delay (or speed up) the feature installation](https://github.com/openhab/openhab-core/blob/11a96d87d6441b6671eee417bcb7f0fd238b9df7/bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java#L165).

Ok, it became a major issue for me as it is systematic.
I propose to add a configuration setting.
If I correctly understand the code you pointed, it starts install features after ONE minute. That is the delay to configure. Are you ok @wborn ? Is it ok to rather consider a delay in seconds ?

**Comment by lolodomo** [comment]
Is there a reason why it starts properly at the third start of OH and not before, or is it just a coincidence ?

**Comment by wborn** [comment]
Most likely the issue will only become worse, because over time there will be more add-ons in the KAR file, so it takes longer to unpack/install it. 

If it cannot be done based on events, I think it would be better to first check the `KarService` if all KAR files in the `/addons` dir are installed, and if so continue installing add-on features. Something similar is already done in the [CommunityKarafAddonHandler](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.addon.marketplace.karaf/src/main/java/org/openhab/core/addon/marketplace/karaf/internal/community/CommunityKarafAddonHandler.java)

**Comment by lolodomo** [comment]
> Most likely the issue will only become worse, because over time there will be more add-ons in the KAR file, so it takes longer to unpack/install it.

Maybe the problem started for me due to more addons included in the kar file than before.

> If it cannot be done based on events, I think it would be better to first check the `KarService` if all KAR files in the `/addons` dir are installed, and if so continue installing add-on features. Something similar is already done in the [CommunityKarafAddonHandler](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.addon.marketplace.karaf/src/main/java/org/openhab/core/addon/marketplace/karaf/internal/community/CommunityKarafAddonHandler.java)

Is it possible for you to work on a solution ? It looks like all this is clearer for you than for me.

**Comment by wborn** [comment]
Currently I have other things I'd like to work on. :wink:

**Comment by lolodomo** [comment]
Setting the first delay to 2 minutes rather than one would solve the problem for everyone ?

**Comment by wborn** [comment]
The timing depends on how fast the hardware is. But if you wait another minute, the `FeatureInstaller` should retry installing features and most likely the KAR should then be installed.

**Comment by lolodomo** [comment]
You are telling me I should just wait and I don't need to restart OH? 
I will try the next time but I believe I already tried that in the past with no success. 
The next time, I will wait at least 10 minutes.
