### ISSUE TITLE
OH3 3.1.0 release UI not working nor Log monitoring

### ISSUE THREAD

**Issue by dertobias** [openhab/openhab-distro#1306]
just upgraded to the newest release (stable) 3.1.0

Main UI not responding, also frontail throws just one error and nothing else.
checked with `sudo service openhab status` and `sudo service frontail status` and those are active running
it also throws just one error:
`2021-06-28 12:07:57.298 [ERROR] [Events.Framework                    ] - FrameworkEvent ERROR

org.osgi.framework.BundleException: Could not resolve module: org.eclipse.xtext.xbase [144]

  Unresolved requirement: Require-Bundle: org.eclipse.xtext.xbase.lib; bundle-version="2.25.0"

  Unresolved requirement: Require-Bundle: org.eclipse.xtext.util

    -> Bundle-SymbolicName: org.eclipse.xtext.util; bundle-version="2.25.0.v20210301-0843"

       org.eclipse.xtext.util [143]

         Unresolved requirement: Require-Bundle: javax.inject; bundle-version="1.0.0"; x-installation:="greedy"; visibility:="reexport"; resolution:="optional"

         Unresolved requirement: Require-Bundle: org.eclipse.xtend.lib

           -> Bundle-SymbolicName: org.eclipse.xtend.lib; bundle-version="2.25.0.v20210301-0821"

              org.eclipse.xtend.lib [138]

                Unresolved requirement: Require-Bundle: org.eclipse.xtext.xbase.lib; bundle-version="2.25.0"; visibility:="reexport"

  Unresolved requirement: Require-Bundle: org.eclipse.xtext.common.types; visibility:="reexport"

    -> Bundle-SymbolicName: org.eclipse.xtext.common.types; bundle-version="2.25.0.v20210301-0909"; singleton:="true"

       org.eclipse.xtext.common.types [141]

         Unresolved requirement: Require-Bundle: org.objectweb.asm; bundle-version="[9.1.0,9.2.0)"

         Unresolved requirement: Require-Bundle: org.eclipse.xtext

           -> Bundle-SymbolicName: org.eclipse.xtext; bundle-version="2.25.0.v20210301-0843"; singleton:="true"

              org.eclipse.xtext [140]

                Unresolved requirement: Require-Bundle: org.objectweb.asm; bundle-version="[9.1.0,9.2.0)"; resolution:="optional"

                Unresolved requirement: Require-Bundle: org.eclipse.emf.mwe.core; bundle-version="1.3.21"; visibility:="reexport"; resolution:="optional"

                Unresolved requirement: Require-Bundle: org.eclipse.emf.mwe.utils; bundle-version="1.3.21"; visibility:="reexport"; resolution:="optional"

                Unresolved requirement: Require-Bundle: org.eclipse.xtend; bundle-version="2.2.0"; resolution:="optional"

                Unresolved requirement: Require-Bundle: org.eclipse.xtend.typesystem.emf; bundle-version="2.2.0"; resolution:="optional"

                Unresolved requirement: Require-Bundle: org.eclipse.core.runtime; bundle-version="3.13.0"; x-installation:="greedy"; resolution:="optional"

                Unresolved requirement: Require-Bundle: org.eclipse.xtend.lib; resolution:="optional"

                  -> Bundle-SymbolicName: org.eclipse.xtend.lib; bundle-version="2.25.0.v20210301-0821"

                Unresolved requirement: Require-Bundle: org.eclipse.xtext.util; visibility:="reexport"

                  -> Bundle-SymbolicName: org.eclipse.xtext.util; bundle-version="2.25.0.v20210301-0843"

  Unresolved requirement: Require-Bundle: org.eclipse.xtext

    -> Bundle-SymbolicName: org.eclipse.xtext; bundle-version="2.25.0.v20210301-0843"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:463) ~[org.eclipse.osgi-3.16.200.jar:?]

	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845) ~[org.eclipse.osgi-3.16.200.jar:?]

	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136) ~[org.eclipse.osgi-3.16.200.jar:?]

	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838) ~[org.eclipse.osgi-3.16.200.jar:?]

	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779) ~[org.eclipse.osgi-3.16.200.jar:?]

	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743) ~[org.eclipse.osgi-3.16.200.jar:?]

	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665) ~[org.eclipse.osgi-3.16.200.jar:?]

	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) ~[org.eclipse.osgi-3.16.200.jar:?]

	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi-3.16.200.jar:?]

	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) [org.eclipse.osgi-3.16.200.jar:?]`
MQTT server seems to be running but rules aren't firing at all nor does persisting any data 
Clearing cache didn‘t do anything
log shows now:

`
tail -f /var/log/openhab/openhab.log /var/log/openhab/events.log

==> /var/log/openhab/openhab.log <==

2021-06-28 16:05:22.814 [WARN ] [org.jline                           ] - The Parser of class org.apache.karaf.shell.impl.console.ConsoleSessionImpl$$Lambda$480/0x61cdb628 does not support the CompletingParsedLine interface. Completion with escaped or quoted words won't work correctly.`

**Comment by dertobias** [comment]
cleared (cleaned) chache via:
`sudo service openhab stop` after that it throwed an error with a solution:
`sudo systemctl daemon-reload`
`sudo service openhab start`
and than rebooted...after that i have the main UI back again.... one item changed (of around 30) than it stopped logging again...no item chage or whatsoever
