### ISSUE TITLE
Snapshot 3340: new Jetty HTTP broke jupnp ? Logs flooded with errors

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#1473]
When I start the last snapshot (3340), my logs are flooded with this error (around 2 stack trace per second):
```
2023-03-03 21:08:09.924 [WARN ] [org.eclipse.jetty.server.HttpChannel] - /upnpcallback/dev/RINCON_000E588EAE6601400/svc/upnp-org/DeviceProperties/event/cb
java.lang.IllegalStateException: !asyncSupported: NotAsync:org.ops4j.pax.web.service.spi.servlet.OsgiInitializedServlet@1a1464b
        at org.eclipse.jetty.server.Request.startAsync(Request.java:2338) ~[?:?]
        at javax.servlet.ServletRequestWrapper.startAsync(ServletRequestWrapper.java:363) ~[bundleFile:4.0.4]
        at org.jupnp.transport.impl.async.AsyncServlet.service(AsyncServlet.java:68) ~[?:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[bundleFile:4.0.4]
        at org.ops4j.pax.web.service.spi.servlet.OsgiInitializedServlet.service(OsgiInitializedServlet.java:102) ~[?:?]
        at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1450) ~[?:?]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[?:?]
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656) ~[?:?]
        at org.ops4j.pax.web.service.spi.servlet.OsgiFilterChain.doFilter(OsgiFilterChain.java:100) ~[?:?]
        at org.ops4j.pax.web.service.jetty.internal.PaxWebServletHandler.doHandle(PaxWebServletHandler.java:310) ~[?:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[?:?]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600) ~[?:?]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[?:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[?:?]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[?:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[?:?]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) ~[?:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[?:?]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505) ~[?:?]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[?:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[?:?]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[?:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[?:?]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234) ~[?:?]
        at org.ops4j.pax.web.service.jetty.internal.PrioritizedHandlerCollection.handle(PrioritizedHandlerCollection.java:96) ~[?:?]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[?:?]
        at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[?:?]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[?:?]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) ~[?:?]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) ~[?:?]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) ~[?:?]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[?:?]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[?:?]
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[?:?]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) ~[bundleFile:9.4.50.v20221201]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) ~[bundleFile:9.4.50.v20221201]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) ~[bundleFile:9.4.50.v20221201]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) ~[bundleFile:9.4.50.v20221201]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) ~[bundleFile:9.4.50.v20221201]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[bundleFile:9.4.50.v20221201]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[bundleFile:9.4.50.v20221201]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
```
Apparently, something new in the new packaged Jetty HTTP client/server broke the jupnp library ?
@wborn ?

**Comment by lolodomo** [comment]
I have plans to submit a lot of PRs tomorrow, this will be finally a weekend without any OH activity for me.
I return to a snapshot before the upgrade to Karaf 4.4.3 (3334).

**Comment by lolodomo** [comment]
If I try again without the Sonos binding, it works, I have no errors logged. I did not test if UPnP discovery is working or not for my other used bindings.
Maybe only UPnP event registration is broken ? It is used by the Sonos binding and few other bindings.

**Comment by J-N-K** [comment]
Discovery works fine, I just checked with the deconz binding.

**Comment by wborn** [comment]
I think jupnp can request the servlet to be async by setting the `async-supported`  service property to `true`, see: https://groups.google.com/g/ops4j/c/E9p7tPydPmo

Usually created servlets do not support async by default unless they are configured otherwise (which depends a bit on the implementation). See also the [ServletRequest#startAsync JavaDocs](https://javadoc.io/static/javax.servlet/javax.servlet-api/4.0.1/javax/servlet/ServletRequest.html#startAsync--)

**Comment by wborn** [comment]
Maybe a change like https://github.com/wborn/jupnp/commit/16d7d7cfb5a749f0d05bd9ed97968d4487534bb5 makes sure async servlets are async. Can you test it @lolodomo?

**Comment by wborn** [comment]
> I have intentions to submit a lot of PRs tomorrow, this will be finally a weekend without any OH activity for me.

Submitting a lot of PRs is a weekend without any OH activity? :laughing:

**Comment by lolodomo** [comment]
> Submitting a lot of PRs is a weekend without any OH activity? 😆

Yes because I was able to make the snapshot working by removing the Sonos binding.

Top priority for me is now to test your fix proposal.

**Comment by lolodomo** [comment]
I forgot how to build jupnp ! I remember that I should not call mvn on the root but I do not remember in what subfolder I must call it. Here is what happen when I try to build in the main branch:
```
$ ls
CONTRIBUTING.md  LICENSE.txt  README.md  bundles/  distribution/  docs/  pom.xml  src/  targetplatform/  tests/  tools/

$ cd bundles/

$ ls
org.jupnp/  org.jupnp.osgi/  org.jupnp.support/  pom.xml

$ mvn clean install
[INFO] Scanning for projects...
[ERROR] Internal error: java.lang.RuntimeException: Could not resolve target platform specification artifact org.jupnp.pom:targetplatform:target:jupnp:2.7.0-SNAPSHOT -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Could not resolve target platform specification artifact org.jupnp.pom:targetplatform:target:jupnp:2.7.0-SNAPSHOT
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:120)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.RuntimeException: Could not resolve target platform specification artifact org.jupnp.pom:targetplatform:target:jupnp:2.7.0-SNAPSHOT
    at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationReader.addTargetArtifact (DefaultTargetPlatformConfigurationReader.java:389)
    at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationReader.setTarget (DefaultTargetPlatformConfigurationReader.java:342)
    at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationReader.getTargetPlatformConfiguration (DefaultTargetPlatformConfigurationReader.java:75)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.setupProject (DefaultTychoResolver.java:87)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead (TychoMavenLifecycleParticipant.java:90)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:264)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
```

**Comment by lolodomo** [comment]
Same result when I try to build from you branch @wborn

**Comment by lolodomo** [comment]
Build is failing at tests stage. But I can retrieve the build jar. Let's see if it works better...

**Comment by lolodomo** [comment]
This is unfortunately not better.
I compiled your branch "async-support" and I finally used the file org.jupnp-2.7.0-SNAPSHOT.jar in org.jupnp/target.
There is also a file org.jupnp.osgi-2.7.0-SNAPSHOT.jar in org.jupnp.osgi/target.
Which one should be used ?

**Comment by lolodomo** [comment]
Bravo and thank you @wborn, looks like you resolved the problem, I have no more the errors and my Sonos things are ONLINE.
Can you please submit the PR ?

**Comment by wborn** [comment]
Thank you for testing the fix @lolodomo. :+1:
Apparently I'm not using any add-on making use of UPnP discovery myself.

**Comment by lolodomo** [comment]
UPnP discovery is apparently not impacted. The problem is rather probably when the binding is subscription to UPnP events. This is the case for Sonos, Wemo, ...

**Comment by lolodomo** [comment]
Snapshot 3344 is still packaged with jupnp version 2.6.1. How to switch to version 2.7.0 ?
