### ISSUE TITLE
whatever this error is its not happy

### ISSUE THREAD

**Issue by blazebrown87221** [openhab/openhab-distro#1547]
here what it spit out 

org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-runtime-base; type=karaf.feature; version="[3.4.4,3.4.4]"; filter:="(&(osgi.identity=openhab-runtime-base)(type=karaf.feature)(version>=3.4.4)(version<=3.4.4))" [caused by: Unable to resolve openhab-runtime-base/3.4.4: missing requirement [openhab-runtime-base/3.4.4] osgi.identity; osgi.identity=openhab-core-model-lsp; type=karaf.feature [caused by: Unable to resolve openhab-core-model-lsp/3.4.4: missing requirement [openhab-core-model-lsp/3.4.4] osgi.identity; osgi.identity=org.openhab.core.model.lsp; type=osgi.bundle; version="[3.4.4,3.4.4]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.core.model.lsp/3.4.4: missing requirement [org.openhab.core.model.lsp/3.4.4] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.openhab.core)(version>=3.4.0)(!(version>=4.0.0)))" [caused by: Unable to resolve org.openhab.core/3.4.4: missing requirement [org.openhab.core/3.4.4] osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"]]]]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
        at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:433)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:420)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:374)
        at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:257)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:399)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve openhab-runtime-base/3.4.4: missing requirement [openhab-runtime-base/3.4.4] osgi.identity; osgi.identity=openhab-core-model-lsp; type=karaf.feature [caused by: Unable to resolve openhab-core-model-lsp/3.4.4: missing requirement [openhab-core-model-lsp/3.4.4] osgi.identity; osgi.identity=org.openhab.core.model.lsp; type=osgi.bundle; version="[3.4.4,3.4.4]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.core.model.lsp/3.4.4: missing requirement [org.openhab.core.model.lsp/3.4.4] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.openhab.core)(version>=3.4.0)(!(version>=4.0.0)))" [caused by: Unable to resolve org.openhab.core/3.4.4: missing requirement [org.openhab.core/3.4.4] osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"]]]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
        ... 12 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve openhab-core-model-lsp/3.4.4: missing requirement [openhab-core-model-lsp/3.4.4] osgi.identity; osgi.identity=org.openhab.core.model.lsp; type=osgi.bundle; version="[3.4.4,3.4.4]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.core.model.lsp/3.4.4: missing requirement [org.openhab.core.model.lsp/3.4.4] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.openhab.core)(version>=3.4.0)(!(version>=4.0.0)))" [caused by: Unable to resolve org.openhab.core/3.4.4: missing requirement [org.openhab.core/3.4.4] osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"]]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
        ... 13 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve org.openhab.core.model.lsp/3.4.4: missing requirement [org.openhab.core.model.lsp/3.4.4] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.openhab.core)(version>=3.4.0)(!(version>=4.0.0)))" [caused by: Unable to resolve org.openhab.core/3.4.4: missing requirement [org.openhab.core/3.4.4] osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
        ... 14 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve org.openhab.core/3.4.4: missing requirement [org.openhab.core/3.4.4] osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
        ... 15 more

**Comment by kaikreuzer** [comment]
It says it cannot find a JavaSE version 11. I'd guess you are starting it with a different (older?) JVM...
