### ISSUE TITLE
Bug executecommandline? - Commands running at the END of Duration.ofSeconds

### ISSUE THREAD

**Issue by erew123** [openhab/openhab-distro#1598]
Ive just upgraded to 4.0.3-1 today. Im working with a DSL rule to run the Samsung smarthings cli to turn a device on/off with an Linux/Ubuntu 22.04 Openhab setup.

At the terminal window, if I manually run my command, it takes 3-4 seconds to execute, and returns a "Command executed successfully".

When I run the command from a rule **(my DSL rules are below)**, the command DOESNT actually run **until** the **Duration.ofSeconds** has elapsed (Easy to spot as the device doesn't turn on or off until that amount of seconds has elapsed). So if I set **Duration.ofSeconds** to 50, then its not until about 50 seconds that my device turns on or off as requested. Set it to 10, then 10 seconds etc.

It does always complete successfully, but I always get an error as follows:

`Timeout occurred when executing commandLine '[sudo, smartthings, devices:commands, g31-MY-DEVICE-ID-HERE-6fl, switch:on, --token=d60-MY-API-KEY-HERE-a7]'`

**It very much appears that its running the command at the END of the timeout, not the start of the Duration.ofSeconds timeout.**

**_My Rules_**

```
if (SoundbarS60APower.state == ON) {executeCommandLine(Duration.ofSeconds(10),"sudo", "smartthings", "devices:commands", "g31-MY-DEVICE-ID-HERE-6fl", "switch:on", "--token=d60-MY-API-KEY-HERE-a7")};
if (SoundbarS60APower.state == OFF) {executeCommandLine(Duration.ofSeconds(10),"sudo", "smartthings", "devices:commands", "g31-MY-DEVICE-ID-HERE-6fl", "switch:off", "--token=d60-MY-API-KEY-HERE-a7")}
```
**_Full error here:_**

```
2023-10-24 01:07:04.532 [WARN ] [ab.core.internal.events.EventHandler] - Dispatching/filtering event for subscriber 'org.openhab.core.events.EventSubscriber' failed: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@11da3266[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@2d48fc89[Wrapped task = org.openhab.core.automation.internal.TriggerHandlerCallbackImpl$TriggerData@34870d60]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@315218b9[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@11da3266[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@2d48fc89[Wrapped task = org.openhab.core.automation.internal.TriggerHandlerCallbackImpl$TriggerData@34870d60]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@315218b9[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:715) ~[?:?]
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:748) ~[?:?]
	at org.openhab.core.automation.internal.TriggerHandlerCallbackImpl.triggered(TriggerHandlerCallbackImpl.java:57) ~[?:?]
	at org.openhab.core.automation.internal.module.handler.ItemStateTriggerHandler.receive(ItemStateTriggerHandler.java:146) ~[?:?]
	at org.openhab.core.internal.events.EventHandler.lambda$2(EventHandler.java:168) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
2023-10-24 01:07:06.534 [WARN ] [rg.openhab.core.io.net.exec.ExecUtil] - Timeout occurred when executing commandLine '[sudo, smartthings, devices:commands, g31-MY-DEVICE-ID-HERE-6fl, switch:on, --token=d60-MY-API-KEY-HERE-a7]'
```
I couldn't spot anything to do with this in the milestone builds fixes, so apologies if Ive missed something!

Thanks

**Comment by florian-h05** [comment]
@kaikreuzer I guess this has to be moved to openHAB core.
