### ISSUE TITLE
java.lang.UnsatisfiedLinkError in systeminfo binding

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-distro#166]
Not sure if this is the place to post it, but as it is a 1.8.0 binding running under Karaf, I get the following at startup:

[I guess the sigar lib is somewhere missing in the jar?]

no libsigar-universal64-macosx.dylib in java.library.path
org.hyperic.sigar.SigarException: no libsigar-universal64-macosx.dylib in java.library.path
	at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:172)
	at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:100)
	at org.openhab.binding.systeminfo.internal.SysteminfoBinding.initializeSystemMonitor(SysteminfoBinding.java:414)
	at org.openhab.binding.systeminfo.internal.SysteminfoBinding.updated(SysteminfoBinding.java:408)
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1444)
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1400)
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:143)
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:110)
	at java.lang.Thread.run(Thread.java:745)
11:12:59.579 [INFO ] [ysteminfo.internal.SysteminfoBinding] - Using Sigar version 1.6.4.129
11:12:59.642 [ERROR] [ysteminfo.internal.SysteminfoBinding] - System monitor error: {}
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Sigar.getNetInterfaceList()[Ljava/lang/String;
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)[168:org.openhab.binding.systeminfo:1.9.0.201604040111]
	at com.sun.proxy.$Proxy117.getNetInterfaceList(Unknown Source)[168:org.openhab.binding.systeminfo:1.9.0.201604040111]
	at org.openhab.binding.systeminfo.internal.SysteminfoBinding.initializeSystemMonitor(SysteminfoBinding.java:424)[168:org.openhab.binding.systeminfo:1.9.0.201604040111]
	at org.openhab.binding.systeminfo.internal.SysteminfoBinding.updated(SysteminfoBinding.java:408)[168:org.openhab.binding.systeminfo:1.9.0.201604040111]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1444)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1400)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:143)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:110)[7:org.apache.felix.configadmin:1.8.8]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_66]

**Comment by kgoderis** [comment]
Ok - found that on the 1.8 wiki page, but can this not be automated in the Karaf world?

**Comment by kgoderis** [comment]
Copying sigar.jar and the relevant .dylib in runtime/karaf/lib/boot does *not* solve the problem

**Comment by kgoderis** [comment]
@dvanherbergen any clue on what to do?

**Comment by kaikreuzer** [comment]
Simply do a 
```
export ${EXTRA_JAVA_OPTS}="-Djava.library.path=<yourpathtothelib>
```

**Comment by kgoderis** [comment]
should java.library.path=/Users/kgoderis/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:. nog contain any of the karaf libs?

**Comment by kgoderis** [comment]
I mean, in a standard setup, should we not auto include a karaf directory of the installation, instead of having to do that manually of include a system/other directory

**Comment by kaikreuzer** [comment]
> contain any of the karaf libs?

Does Karaf have any native binaries that need to be included?

In openHAB 1, we had the ${openhab.home}/lib folder that was automatically included. But for OH2, we should rather try to have native libs packaged within the OSGi bundles as it otherwise blocks the automatic provisioning.
Btw, did you also check out https://github.com/openhab/openhab2-addons/issues/365?

**Comment by kgoderis** [comment]
> Btw, did you also check out openhab/openhab2-addons#365?

not yet, as it is not in the official repo. I doing a clean sheet install with the online distro just to test out the complete environment as it is. 

you are right on the OSGi bundle in fact, maybe bundle all .dylibs for all platforms (temporarily) could be a solution as well. Got it working in the meantime

**Comment by watou** [comment]
I have an improved packaging for the systeminfo binding [here](https://github.com/openhab/openhab/pull/4183) that removes the need to handle native libraries for this binding, unless you are on ARM.  Just install the bundle in the OSGi container and it works.  Could you try it?

**Comment by kaikreuzer** [comment]
@kgoderis ok to close this issue?

**Comment by foxytocin** [comment]
On Rapsberry Pi i added "variant=raspbian" to the "systeminfo.cfg" in OH2/conf/services/ folder.
That did the job without adding any libs eg. manual.

**Comment by watou** [comment]
> That did the job without adding any libs eg. manual.

Excellent!

**Comment by kaikreuzer** [comment]
So can we close this issue then @kgoderis?
