### ISSUE TITLE
Error downloading mvn:org.openhab.addons.bundles/org.openhab.persistence.inmemory/4.2.0

### ISSUE THREAD

**Issue by Summm1t** [openhab/openhab-distro#1670]
I unpacked the Openhab bundle [(4.2.0)](https://github.com/openhab/openhab-distro/releases/download/4.2.0/openhab-4.2.0.zip) and started with start_debug. 
Then, I tailed the logs, and went through the wizard with all defaults. There's a question to add persistence. All 3 choices are selected by default. When I go further in the wizard, I get the following exception:
```
22:46:48.080 [INFO ] [org.openhab.core.Activator           ] - Starting openHAB 4.2.0 (Release Build)
22:46:49.911 [WARN ] [org.openhab.core.net.NetUtil         ] - Found multiple local interfaces - ignoring 192.168.1.13
22:46:50.569 [INFO ] [b.core.model.lsp.internal.ModelServer] - Started Language Server Protocol (LSP) service on port 5007
22:46:55.283 [INFO ] [re.automation.internal.RuleEngineImpl] - Rule engine started.
22:47:16.027 [WARN ] [e.io.rest.auth.internal.TokenResource] - Couldn't find a user with a session matching the provided refresh_token
22:47:16.034 [WARN ] [e.io.rest.auth.internal.TokenResource] - Token issuing failed: invalid_grant
22:47:37.277 [INFO ] [tp.auth.internal.AuthorizePageServlet] - First user account created: openhab
22:47:48.037 [INFO ] [b.core.internal.i18n.I18nProviderImpl] - Time zone set to 'Europe/Brussels'.
22:47:48.039 [INFO ] [b.core.internal.i18n.I18nProviderImpl] - Locale set to 'en_BE'.
22:48:21.802 [INFO ] [b.core.internal.i18n.I18nProviderImpl] - Location set to '50.798123424528,3.966751098632813'.
org.apache.karaf.features.internal.util.MultiException: Error:
	Error downloading mvn:org.openhab.addons.bundles/org.openhab.persistence.inmemory/4.2.0
	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.<init>(MavenDownloadManager.java:91)
	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager.createDownloader(MavenDownloadManager.java:72)
	at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:474)
	at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:469)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:223)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:399)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
	Suppressed: java.io.IOException: Error downloading mvn:org.openhab.addons.bundles/org.openhab.persistence.inmemory/4.2.0
		at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:77)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
		... 3 more
	Caused by: java.io.IOException: Error resolving artifact org.openhab.addons.bundles:org.openhab.persistence.inmemory:jar:4.2.0: [Could not find artifact org.openhab.addons.bundles:org.openhab.persistence.inmemory:jar:4.2.0 in bosa-nexus-group (https://devops.digital.belgium.be/nexus/repository/maven-public/)]
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.configureIOException(AetherBasedResolver.java:803)
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:774)
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:657)
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:598)
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:565)
		at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:52)
		at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)
		... 6 more

```

**Comment by kaikreuzer** [comment]
```
in bosa-nexus-group (https://devops.digital.belgium.be/nexus/repository/maven-public/
```
You seem to have special Maven settings that prevent looking into our openHAB Artifactory for the add-ons.
Could you please check this?

**Comment by Summm1t** [comment]
Well, changing the maven settings did the trick. Thanks a lot @kaikreuzer !
