### ISSUE TITLE
Build of the night failed

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#1673]
Snapshot 4190:
```
Started by upstream project "[openHAB-Addons](https://ci.openhab.org/job/openHAB-Addons/)" build number [1454](https://ci.openhab.org/job/openHAB-Addons/1454)
originally caused by:
 Started by an SCM change
Running as SYSTEM
[EnvInject] - Loading node environment variables.
Building on the built-in node in workspace /var/jenkins_home/workspace/openHAB-Distribution
The recommended git tool is: git
No credentials specified
 > git rev-parse --resolve-git-dir /var/jenkins_home/workspace/openHAB-Distribution/.git # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/openhab/openhab-distro # timeout=10
Fetching upstream changes from https://github.com/openhab/openhab-distro
 > git --version # timeout=10
 > git --version # 'git version 2.39.2'
 > git fetch --tags --force --progress -- https://github.com/openhab/openhab-distro +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/main^{commit} # timeout=10
Checking out Revision 22c0a1e51bd660b643cffe007c1035af177b0b92 (refs/remotes/origin/main)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 22c0a1e51bd660b643cffe007c1035af177b0b92 # timeout=10
Commit message: "Archive released distro artifacts (#1672)"
 > git rev-list --no-walk 22c0a1e51bd660b643cffe007c1035af177b0b92 # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
Resetting working tree
 > git reset --hard # timeout=10
 > git clean -fdx # timeout=10
[openHAB-Distribution] $ /bin/bash -xe /tmp/jenkins6977176090983632429.sh
+ rm -rf /var/jenkins_home/maven-repositories/1/org/openhab
+ rm -rf /var/jenkins_home/jenkins-built-in/maven-repositories/1/org/openhab
Parsing POMs
Downloaded artifact https://repo.maven.apache.org/maven2/org/openhab/openhab-super-pom/maven-metadata.xml
ERROR: Processing failed due to a bug in the code. Please report this to the issue tracker (https://jenkins.io/redirect/report-an-issue).
java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
	at java.base/java.util.Properties.loadConvert(Unknown Source)
	at java.base/java.util.Properties.load0(Unknown Source)
	at java.base/java.util.Properties.load(Unknown Source)
	at org.jfrog.build.extractor.BuildInfoExtractorUtils.searchAdditionalPropertiesFile(BuildInfoExtractorUtils.java:113)
	at org.jfrog.build.extractor.BuildInfoExtractorUtils.mergePropertiesWithSystemAndPropertyFile(BuildInfoExtractorUtils.java:70)
	at org.jfrog.build.extractor.maven.resolver.ResolutionHelper.init(ResolutionHelper.java:31)
	at org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseResolversHelper.initResolutionHelper(ArtifactoryEclipseResolversHelper.java:67)
	at org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseResolversHelper.getResolutionRepositories(ArtifactoryEclipseResolversHelper.java:45)
	at org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseArtifactResolver.enforceResolutionRepositories(ArtifactoryEclipseArtifactResolver.java:36)
	at org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseArtifactResolver.resolveArtifacts(ArtifactoryEclipseArtifactResolver.java:53)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:212)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:272)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:192)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:242)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1077)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:853)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:344)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:252)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:448)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:414)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:377)
	at org.jfrog.build.extractor.maven.ArtifactoryProjectBuilder.build(ArtifactoryProjectBuilder.java:47)
	at hudson.maven.MavenEmbedder.buildProjects(MavenEmbedder.java:370)
	at hudson.maven.MavenEmbedder.readProjects(MavenEmbedder.java:340)
	at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:1330)
	at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:1124)
	at hudson.FilePath.act(FilePath.java:1232)
	at hudson.FilePath.act(FilePath.java:1215)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.parsePoms(MavenModuleSetBuild.java:985)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:689)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:526)
	at hudson.model.Run.execute(Run.java:1894)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
project=hudson.maven.MavenModuleSet@5b03ebf4[openHAB-Distribution]
project.getModules()=[hudson.maven.MavenModule@17539d6d[openHAB-Distribution/org.openhab.distro:addons][openHAB-Distribution/org.openhab.distro:addons][relativePath:features/addons], hudson.maven.MavenModule@302bd997[openHAB-Distribution/org.openhab.distro:distro][openHAB-Distribution/org.openhab.distro:distro][relativePath:features/distro], hudson.maven.MavenModule@7ed6d4b1[openHAB-Distribution/org.openhab.distro:distro-kar][openHAB-Distribution/org.openhab.distro:distro-kar][relativePath:features/distro-kar], hudson.maven.MavenModule@58f19b52[openHAB-Distribution/org.openhab.distro:openhab][openHAB-Distribution/org.openhab.distro:openhab][relativePath:distributions/openhab], hudson.maven.MavenModule@5342ddd4[openHAB-Distribution/org.openhab.distro:openhab-addons][openHAB-Distribution/org.openhab.distro:openhab-addons][relativePath:distributions/openhab-addons], hudson.maven.MavenModule@3d4b514a[openHAB-Distribution/org.openhab.distro:openhab-demo][openHAB-Distribution/org.openhab.distro:openhab-demo][relativePath:distributions/openhab-demo], hudson.maven.MavenModule@7570690e[openHAB-Distribution/org.openhab.distro:openhab-verify][openHAB-Distribution/org.openhab.distro:openhab-verify][relativePath:distributions/openhab-verify], hudson.maven.MavenModule@218f57f9[openHAB-Distribution/org.openhab.distro:pom][openHAB-Distribution/org.openhab.distro:pom][relativePath:], hudson.maven.MavenModule@64668261[openHAB-Distribution/org.openhab.distro:pom-distributions][openHAB-Distribution/org.openhab.distro:pom-distributions][relativePath:distributions], hudson.maven.MavenModule@3404ea6[openHAB-Distribution/org.openhab.distro:pom-features][openHAB-Distribution/org.openhab.distro:pom-features][relativePath:features]]
project.getRootModule()=hudson.maven.MavenModule@218f57f9[openHAB-Distribution/org.openhab.distro:pom][openHAB-Distribution/org.openhab.distro:pom][relativePath:]
FATAL: Malformed \uxxxx encoding.
java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
	at java.base/java.util.Properties.loadConvert(Unknown Source)
	at java.base/java.util.Properties.load0(Unknown Source)
	at java.base/java.util.Properties.load(Unknown Source)
	at org.jfrog.build.extractor.BuildInfoExtractorUtils.searchAdditionalPropertiesFile(BuildInfoExtractorUtils.java:113)
	at org.jfrog.build.extractor.BuildInfoExtractorUtils.mergePropertiesWithSystemAndPropertyFile(BuildInfoExtractorUtils.java:70)
	at org.jfrog.build.extractor.maven.resolver.ResolutionHelper.init(ResolutionHelper.java:31)
	at org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseResolversHelper.initResolutionHelper(ArtifactoryEclipseResolversHelper.java:67)
	at org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseResolversHelper.getResolutionRepositories(ArtifactoryEclipseResolversHelper.java:45)
	at org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseArtifactResolver.enforceResolutionRepositories(ArtifactoryEclipseArtifactResolver.java:36)
	at org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseArtifactResolver.resolveArtifacts(ArtifactoryEclipseArtifactResolver.java:53)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:212)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:272)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:192)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:242)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1077)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:853)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:344)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:252)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:448)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:414)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:377)
	at org.jfrog.build.extractor.maven.ArtifactoryProjectBuilder.build(ArtifactoryProjectBuilder.java:47)
	at hudson.maven.MavenEmbedder.buildProjects(MavenEmbedder.java:370)
	at hudson.maven.MavenEmbedder.readProjects(MavenEmbedder.java:340)
	at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:1330)
	at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:1124)
	at hudson.FilePath.act(FilePath.java:1232)
	at hudson.FilePath.act(FilePath.java:1215)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.parsePoms(MavenModuleSetBuild.java:985)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:689)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:526)
	at hudson.model.Run.execute(Run.java:1894)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
Archiving artifacts
[Slack Notifications] found #4189 as previous completed, non-aborted build
Finished: FAILURE
```

A link with #1672 merged yesterday ?

**Comment by lolodomo** [comment]
@wborn @kaikreuzer for information

**Comment by wborn** [comment]
No that job doesn't use the pipeline. It's similar to https://github.com/jfrog/jenkins-artifactory-plugin/issues/913

Already cleared that plugins cache and also all local Maven repos in case some corrupted file ended up in there. I'll have another look. Would be nice if the stack trace would include the file causing the exception. 🙃

**Comment by lolodomo** [comment]
Build succeeded last night.
