### ISSUE TITLE
Latest Snapshot #242 - [ERROR] [org.apache.felix.configadmin] - org.osgi.service.cm.ManagedService

### ISSUE THREAD

**Issue by foxytocin** [openhab/openhab-distro#177]
```
07:10:26.915 [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.cm.ManagedService, id=234, bundle=115/mvn:org.eclipse.smarthome.model/org.eclipse.smarthome.model.core/0.8.0-SNAPSHOT]: Unexpected problem updating configuration org.eclipse.smarthome.folder
java.util.ConcurrentModificationException
	at org.eclipse.emf.common.util.AbstractEList$EIterator.checkModCount(AbstractEList.java:758)[62:org.eclipse.emf.common:2.11.0.v20150805-0538]
	at org.eclipse.emf.common.util.AbstractEList$EIterator.doNext(AbstractEList.java:706)[62:org.eclipse.emf.common:2.11.0.v20150805-0538]
	at org.eclipse.emf.common.util.AbstractEList$EIterator.next(AbstractEList.java:692)[62:org.eclipse.emf.common:2.11.0.v20150805-0538]
	at org.eclipse.xtext.resource.SynchronizedXtextResourceSet$1$SynchronizedEIterator.next(SynchronizedXtextResourceSet.java:188)[134:org.eclipse.xtext:2.9.2]
	at org.eclipse.xtext.resource.SynchronizedXtextResourceSet$1$SynchronizedEIterator.next(SynchronizedXtextResourceSet.java:1)[134:org.eclipse.xtext:2.9.2]
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:644)[17:com.google.guava:10.0.1.v201203051515]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)[17:com.google.guava:10.0.1.v201203051515]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)[17:com.google.guava:10.0.1.v201203051515]
	at com.google.common.collect.Iterators$8.hasNext(Iterators.java:777)[17:com.google.guava:10.0.1.v201203051515]
	at com.google.common.collect.Lists.newArrayList(Lists.java:138)[17:com.google.guava:10.0.1.v201203051515]
	at com.google.common.collect.Lists.newArrayList(Lists.java:119)[17:com.google.guava:10.0.1.v201203051515]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.getAllModelNamesOfType(ModelRepositoryImpl.java:156)[115:org.eclipse.smarthome.model.core:0.8.0.201604151434]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.getAll(GenericItemProvider.java:123)[116:org.eclipse.smarthome.model.item:0.8.0.201604151434]
	at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.allItemsChanged(ItemRegistryImpl.java:87)[96:org.eclipse.smarthome.core:0.8.0.201604151434]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:407)[116:org.eclipse.smarthome.model.item:0.8.0.201604151434]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:200)[115:org.eclipse.smarthome.model.core:0.8.0.201604151434]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:97)[115:org.eclipse.smarthome.model.core:0.8.0.201604151434]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:240)[115:org.eclipse.smarthome.model.core:0.8.0.201604151434]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.notifyUpdateToModelRepo(FolderObserver.java:169)[115:org.eclipse.smarthome.model.core:0.8.0.201604151434]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.updated(FolderObserver.java:150)[115:org.eclipse.smarthome.model.core:0.8.0.201604151434]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1444)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1400)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:143)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:110)[7:org.apache.felix.configadmin:1.8.8]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
```

**Comment by maggu2810** [comment]
Are you using the Oracle Java VM or the OpenJDK one?

**Comment by foxytocin** [comment]
Hi,
Raspbian Jessie Lite with
```
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)
```

Since 1-2 weeks at openhab-startup it's showing
`[arthome.core.internal.PortableBase64] - PortableBase64 class is running on JavaSE >=8`

Thats "new". In the past there wasn't this "PortableBase64 class is running on JavaSE >=8". But thats not the problem! Because even with that everything worked till updating tonight. I'am updating nearly every snapshot, so that just since #240 / #242

**Comment by kaikreuzer** [comment]
> Since 1-2 weeks at openhab-startup it's showing
> ```[arthome.core.internal.PortableBase64] - PortableBase64 class is running on JavaSE >=8```

That logging is already suppressed in the latest snapshot through https://github.com/eclipse/smarthome/pull/1386.

Is the ConcurrentModificationException reproducible? Looks like a race condition that might only happen once in a while?

**Comment by foxytocin** [comment]
Not sure about this. Happens directly with https://github.com/openhab/openhab-distro/issues/176 this.
Maybe thats just happens accidental. I'am now using a backup from tonight. Will have a look on that with the next snapshot.

**Comment by foxytocin** [comment]
ConcurrentModificationException isn't reproducible. I always do have a lot of WARN at initial startup after updating so the newest snapshot. Because bindings are not installed, imports are missing eg.. But after this first startup everything is "clean" right now.
