### ISSUE TITLE
Snapshot #246 + #248 -  [ERROR] [ome.core.thing.internal.ThingManager]

### ISSUE THREAD

**Issue by foxytocin** [openhab/openhab-distro#184]
```
13:01:03.313 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured during notification about bridge status change on thing 'zwave:device:153e307c039:node3': null
java.lang.NullPointerException
	at org.openhab.binding.zwave.handler.ZWaveThingHandler.initialiseNode(ZWaveThingHandler.java:155)[162:org.openhab.binding.zwave:2.0.0.201604180954]
	at org.openhab.binding.zwave.handler.ZWaveThingHandler.bridgeStatusChanged(ZWaveThingHandler.java:422)[162:org.openhab.binding.zwave:2.0.0.201604180954]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$13.run(ThingManager.java:820)[102:org.eclipse.smarthome.core.thing:0.8.0.201604151434]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_65]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
```

Z-Wave Controller is still working. DEBUG shows that all the data is reported correctly. Also data from all nodes are incoming. But openhab doesn't react to them (don't updates items).
In Habmin2 controller is marked as working. All the nodes are "false / red". Removing and readding one node worked for 10 seconds. Becomes "green" and then false back to "false / red".

**Comment by kaikreuzer** [comment]
This should rather go to https://github.com/openhab/openhab2-addons/issues, since it is related to the ZWave binding.
