### ISSUE TITLE
[.core.transform.TransformationHelper] - Cannot get service reference for transformation service of type MAP

### ISSUE THREAD

**Issue by lsafelix75** [openhab/openhab-distro#199]
I am getting error on openhab2 latest distro snapshot (#273) but it is running fine on Eclipse IDE. Any reason why? Thanks

**Comment by kaikreuzer** [comment]
Did you install the MAP transformation service?

**Comment by lsafelix75** [comment]
Thanks for the advice. I did try to enable the service with feature:install esh-transform-map. But, now my custom binding generates this error. The binding worked fine before installing the map and also on Eclipse IDE (local execution). 

java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.eclipse.smarthome.config.core.Configuration.get(Ljava/lang/Object;)Ljava/lang/Object;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)[:1.8.0]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:179)[96:org.eclipse.smarthome.core:0.8.0.201604302105]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:72)[96:org.eclipse.smarthome.core:0.8.0.201604302105]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:56)[96:org.eclipse.smarthome.core:0.8.0.201604302105]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$7.run(ThingManager.java:659)[102:org.eclipse.smarthome.core.thing:0.8.0.201604302105]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0]
	at java.lang.Thread.run(Thread.java:744)[:1.8.0]
Caused by: java.lang.NoSuchMethodError: org.eclipse.smarthome.config.core.Configuration.get(Ljava/lang/Object;)Ljava/lang/Object;
	at org.openhab.binding.talentswitchmqtt.handler.BrokerHandler.initialize(BrokerHandler.java:82)
	at org.eclipse.smarthome.core.thing.internal.ThingManager$7$1.call(ThingManager.java:662)
	at org.eclipse.smarthome.core.thing.internal.ThingManager$7$1.call(ThingManager.java:1)
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:170)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0]
	... 3 more

**Comment by kaikreuzer** [comment]
Looks like the same error as https://github.com/eclipse/smarthome/issues/1437, where we still have to figure out, why this happens - usually, a recompilation against the latest target platform should help, I would hope.

**Comment by kaikreuzer** [comment]
P.S.: Note that you can also install the MAP service through the Paper UI -> Extensions -> Transformations -> MAP
