### ISSUE TITLE
shell:threads throws NPE

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-distro#246]
openhab> shell:threads
Error executing command: java.lang.NullPointerException

2016-07-05 17:37:05.859 [ERROR] [apache.karaf.shell.support.ShellUtil] - Exception caught while executing command
java.lang.NullPointerException
	at org.apache.karaf.shell.commands.impl.ThreadsAction$ThreadData.isInteresting(ThreadsAction.java:242)[63:org.apache.karaf.shell.commands:4.0.4]
	at org.apache.karaf.shell.commands.impl.ThreadsAction$ThreadGroupData.hasInterestingThreads(ThreadsAction.java:202)[63:org.apache.karaf.shell.commands:4.0.4]
	at org.apache.karaf.shell.commands.impl.ThreadsAction$ThreadGroupData.printDump(ThreadsAction.java:188)[63:org.apache.karaf.shell.commands:4.0.4]
	at org.apache.karaf.shell.commands.impl.ThreadsAction$ThreadGroupData.print(ThreadsAction.java:169)[63:org.apache.karaf.shell.commands:4.0.4]
	at org.apache.karaf.shell.commands.impl.ThreadsAction.execute(ThreadsAction.java:119)[63:org.apache.karaf.shell.commands:4.0.4]
	at org.apache.karaf.shell.impl.action.command.ActionCommand.execute(ActionCommand.java:83)[64:org.apache.karaf.shell.core:4.0.4]
	at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:67)[64:org.apache.karaf.shell.core:4.0.4]
	at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:87)[64:org.apache.karaf.shell.core:4.0.4]
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:480)[64:org.apache.karaf.shell.core:4.0.4]
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:406)[64:org.apache.karaf.shell.core:4.0.4]
	at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)[64:org.apache.karaf.shell.core:4.0.4]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:182)[64:org.apache.karaf.shell.core:4.0.4]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:119)[64:org.apache.karaf.shell.core:4.0.4]
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:94)[64:org.apache.karaf.shell.core:4.0.4]
	at org.apache.karaf.shell.impl.console.ConsoleSessionImpl.run(ConsoleSessionImpl.java:270)[64:org.apache.karaf.shell.core:4.0.4]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_66]

**Comment by kaikreuzer** [comment]
There isn't a single class of ESH/OH2 involved in your stack. Shouldn't you rather report this at Karaf?

**Comment by kgoderis** [comment]
Maybe indeed, but as we have some Karaf experts following this forum/repo....

**Comment by maggu2810** [comment]
The current 4.0.x Karaf version is 4.0.5 (and IIRC at the end of this week the 4.0.6 release is prepared).
As I am using already 4.0.5 (for a non-OH runtime) I gave it a try and executed "shell:threads".
No NPE has been thrown.

@kgoderis Can you test K405 for OH and give here some feedback?

**Comment by kgoderis** [comment]
@maggu2810 How do bump up the version of Karaf used? simply via a bundle:update?

**Comment by maggu2810** [comment]
A simple test could be done using:
https://github.com/openhab/openhab-distro/blob/440203d/pom.xml#L59

If this solves the NPE, it is rather clear, that it is caused by the Karaf version.

OH modifies some stuff, so if the NPE still occurs but not in the official K405 distribution I assume it is caused by the modifications.

But perhaps it would be easier to test the official runtime of Karaf 4.0.4 and 4.0.5 first (or have a look at the Karaf Jira).

**Comment by maggu2810** [comment]
Official K404 does not throw a NPE on "shell:threads".

Perhaps a special thread name or other stuff is involved.
I assume it is necessary to debug the container and inspect the error in the code (if there is no Jira about).

**Comment by maggu2810** [comment]
@kgoderis Any news?

**Comment by kgoderis** [comment]
I have not made any progress on this issue (yet).
