### ISSUE TITLE
Could not find artifact org.openhab.distro:openhab-aggregate-xml:xml:features:2.0.0.b3 in oh-releases-repo 

### ISSUE THREAD

**Issue by ollie-dev** [openhab/openhab-distro#283]
Upgrading from beta3 to beta4 on ubuntu lead to the following error:
`2016-09-16 12:07:19.281 [WARN ] [url.mvn.internal.AetherBasedResolver] - Error resolving artifactorg.openhab.distro:openhab-aggregate-xml:xml:features:2.0.0.b3:Could not find artifact org.openhab.distro:openhab-aggregate-xml:xml:features:2.0.0.b3 in oh-releases-repo (https://jcenter.bintray.com/)
shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.openhab.distro:openhab-aggregate-xml:xml:features:2.0.0.b3 in oh-releases-repo (https://jcenter.bintray.com/)
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)[4:org.ops4j.pax.url.mvn:2.4.5]
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)[4:org.ops4j.pax.url.mvn:2.4.5]
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)[4:org.ops4j.pax.url.mvn:2.4.5]
	at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)[4:org.ops4j.pax.url.mvn:2.4.5]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:615)[4:org.ops4j.pax.url.mvn:2.4.5]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:570)[4:org.ops4j.pax.url.mvn:2.4.5]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:548)[4:org.ops4j.pax.url.mvn:2.4.5]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:523)[4:org.ops4j.pax.url.mvn:2.4.5]
	at org.ops4j.pax.url.mvn.internal.Connection.getInputStream(Connection.java:123)[4:org.ops4j.pax.url.mvn:2.4.5]
	at java.net.URL.openStream(URL.java:1045)[:1.8.0_101]
	at org.apache.karaf.features.internal.service.RepositoryImpl.load(RepositoryImpl.java:91)[9:org.apache.karaf.features.core:4.0.4]
	at org.apache.karaf.features.internal.service.RepositoryImpl.load(RepositoryImpl.java:85)[9:org.apache.karaf.features.core:4.0.4]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.getFeatures(FeaturesServiceImpl.java:637)[9:org.apache.karaf.features.core:4.0.4]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.listInstalledFeatures(FeaturesServiceImpl.java:682)[9:org.apache.karaf.features.core:4.0.4]
	at org.openhab.core.karaf.internal.FeatureInstaller.isInstalled(FeatureInstaller.java:309)[162:org.openhab.core.karaf:2.0.0.b3]
	at org.openhab.core.karaf.internal.FeatureInstaller.installFeature(FeatureInstaller.java:274)[162:org.openhab.core.karaf:2.0.0.b3]
	at org.openhab.core.karaf.internal.FeatureInstaller.installPackage(FeatureInstaller.java:287)[162:org.openhab.core.karaf:2.0.0.b3]
	at org.openhab.core.karaf.internal.FeatureInstaller.access$3(FeatureInstaller.java:283)[162:org.openhab.core.karaf:2.0.0.b3]
	at org.openhab.core.karaf.internal.FeatureInstaller$1.run(FeatureInstaller.java:127)[162:org.openhab.core.karaf:2.0.0.b3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_101]
Caused by: shaded.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.openhab.distro:openhab-aggregate-xml:xml:features:2.0.0.b3 in oh-releases-repo (https://jcenter.bintray.com/)
	at shaded.org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)[4:org.ops4j.pax.url.mvn:2.4.5]
	at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)[4:org.ops4j.pax.url.mvn:2.4.5]
	at shaded.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)[4:org.ops4j.pax.url.mvn:2.4.5]
	at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)[4:org.ops4j.pax.url.mvn:2.4.5]
	at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)[4:org.ops4j.pax.url.mvn:2.4.5]
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)[4:org.ops4j.pax.url.mvn:2.4.5]
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)[4:org.ops4j.pax.url.mvn:2.4.5]
	... 21 more
`

I found out, that https://jcenter.bintray.com/org/openhab/distro/openhab-aggregate-xml/ simply misses the beta3 version and only holds beta1 and beta4.

@theoweiss, maybe you could help here?

**Comment by theoweiss** [comment]
Hi @ollie-dev,

thanks for the report. 
We've seen similar errors when testing the released b4 packages and had a first guess that deleting /var/lib/openhab2/cache could help out.  Here 
https://community.openhab.org/t/noclassdeffounderror-when-starting-zwave-binding-after-upgrading-to-oh2-beta-4/14159/4?u=theo a user reported that removing the cache fixed the issue. 

Could you please try wether the errors disappear if you `rm -rf /var/lib/openhab2/cache` and restart openHAB?

Regards,
Theo

**Comment by ollie-dev** [comment]
Hi @theoweiss,

that helped getting rid of those errors in the logs. However, all my bindings are gone and I have to reinstall them via PaperUI. Seems like they then work again with the former configuration, so thats no prob. But normally bindings should upgrade automatically and work like before, right?

Thanks for your hints!
Best regards
Ollie

**Comment by kaikreuzer** [comment]
> But normally bindings should upgrade automatically and work like before, right?

The best way to achieve this for now is to enter the addons that you are using in conf/services/addons.cfg - this should make sure that they are re-installed after an upgrade.
