### ISSUE TITLE
RuleEngine install fails

### ISSUE THREAD

**Issue by SuperOok** [openhab/openhab-distro#290]
I did a fresh install of the snapshot builds via apt-get repository on a Raspberry Pi2 precisely following the [linux installation guide](http://docs.openhab.org/installation/linux.html).

In paperui I enabled experimental features and tried to install the rule-engine via Paper UI. I get this exception:

`01:17:47.251 [WARN ] [url.mvn.internal.AetherBasedResolver] - Error resolving artifactorg.openhab.distro:openhab-aggregate-xml:xml:features:2.0.0.b3:Could not find artifact org.openhab.distro:openhab-aggregate-xml:xml:features:2.0.0.b3 in oh-releases-repo (https://jcenter.bintray.com/)
shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.openhab.distro:openhab-aggregate-xml:xml:features:2.0.0.b3 in oh-releases-repo (https://jcenter.bintray.com/)
        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)[4:org.ops4j.pax.url.mvn:2.4.5]
        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)[4:org.ops4j.pax.url.mvn:2.4.5]
        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)[4:org.ops4j.pax.url.mvn:2.4.5]
        at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)[4:org.ops4j.pax.url.mvn:2.4.5]
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:615)[4:org.ops4j.pax.url.mvn:2.4.5]
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:570)[4:org.ops4j.pax.url.mvn:2.4.5]
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:548)[4:org.ops4j.pax.url.mvn:2.4.5]
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:523)[4:org.ops4j.pax.url.mvn:2.4.5]
        at org.ops4j.pax.url.mvn.internal.Connection.getInputStream(Connection.java:123)[4:org.ops4j.pax.url.mvn:2.4.5]
        at java.net.URL.openStream(URL.java:1038)[:1.8.0_65]
        at org.apache.karaf.features.internal.service.RepositoryImpl.load(RepositoryImpl.java:91)[9:org.apache.karaf.features.core:4.0.4]
        at org.apache.karaf.features.internal.service.RepositoryImpl.load(RepositoryImpl.java:85)[9:org.apache.karaf.features.core:4.0.4]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.getFeatures(FeaturesServiceImpl.java:637)[9:org.apache.karaf.features.core:4.0.4]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.listInstalledFeatures(FeaturesServiceImpl.java:682)[9:org.apache.karaf.features.core:4.0.4]
        at org.openhab.core.karaf.internal.FeatureInstaller.isInstalled(FeatureInstaller.java:309)[162:org.openhab.core.karaf:2.0.0.b3]
        at org.openhab.core.karaf.internal.FeatureInstaller.installFeature(FeatureInstaller.java:274)[162:org.openhab.core.karaf:2.0.0.b3]
        at org.openhab.core.karaf.internal.FeatureInstaller.installPackage(FeatureInstaller.java:287)[162:org.openhab.core.karaf:2.0.0.b3]
        at org.openhab.core.karaf.internal.FeatureInstaller.access$3(FeatureInstaller.java:283)[162:org.openhab.core.karaf:2.0.0.b3]
        at org.openhab.core.karaf.internal.FeatureInstaller$1.run(FeatureInstaller.java:127)[162:org.openhab.core.karaf:2.0.0.b3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
Caused by: shaded.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.openhab.distro:openhab-aggregate-xml:xml:features:2.0.0.b3 in oh-releases-repo (https://jcenter.bintray.com/)
        at shaded.org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)[4:org.ops4j.pax.url.mvn:2.4.5]
        at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)[4:org.ops4j.pax.url.mvn:2.4.5]
        at shaded.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)[4:org.ops4j.pax.url.mvn:2.4.5]
        at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)[4:org.ops4j.pax.url.mvn:2.4.5]
        at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)[4:org.ops4j.pax.url.mvn:2.4.5]
        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)[4:org.ops4j.pax.url.mvn:2.4.5]
        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)[4:org.ops4j.pax.url.mvn:2.4.5]
        ... 21 more
01:17:47.263 [WARN ] [internal.service.FeaturesServiceImpl] - Can't load features repository mvn:org.openhab.distro/openhab-aggregate-xml/2.0.0.b3/xml/features
java.io.IOException: Error resolving artifact org.openhab.distro:openhab-aggregate-xml:xml:features:2.0.0.b3: Could not find artifact org.openhab.distro:openhab-aggregate-xml:xml:features:2.0.0.b3 in oh-releases-repo (https://jcenter.bintray.com/) : mvn:org.openhab.distro/openhab-aggregate-xml/2.0.0.b3/xml/features
        at org.apache.karaf.features.internal.service.RepositoryImpl.load(RepositoryImpl.java:96)[9:org.apache.karaf.features.core:4.0.4]
        at org.apache.karaf.features.internal.service.RepositoryImpl.load(RepositoryImpl.java:85)[9:org.apache.karaf.features.core:4.0.4]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.getFeatures(FeaturesServiceImpl.java:637)[9:org.apache.karaf.features.core:4.0.4]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.listInstalledFeatures(FeaturesServiceImpl.java:682)[9:org.apache.karaf.features.core:4.0.4]
        at org.openhab.core.karaf.internal.FeatureInstaller.isInstalled(FeatureInstaller.java:309)[162:org.openhab.core.karaf:2.0.0.b3]
        at org.openhab.core.karaf.internal.FeatureInstaller.installFeature(FeatureInstaller.java:274)[162:org.openhab.core.karaf:2.0.0.b3]
        at org.openhab.core.karaf.internal.FeatureInstaller.installPackage(FeatureInstaller.java:287)[162:org.openhab.core.karaf:2.0.0.b3]
        at org.openhab.core.karaf.internal.FeatureInstaller.access$3(FeatureInstaller.java:283)[162:org.openhab.core.karaf:2.0.0.b3]
        at org.openhab.core.karaf.internal.FeatureInstaller$1.run(FeatureInstaller.java:127)[162:org.openhab.core.karaf:2.0.0.b3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
Caused by: java.io.IOException: Error resolving artifact org.openhab.distro:openhab-aggregate-xml:xml:features:2.0.0.b3: Could not find artifact org.openhab.distro:openhab-aggregate-xml:xml:features:2.0.0.b3 in oh-releases-repo (https://jcenter.bintray.com/)
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:626)[4:org.ops4j.pax.url.mvn:2.4.5]
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:570)[4:org.ops4j.pax.url.mvn:2.4.5]
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:548)[4:org.ops4j.pax.url.mvn:2.4.5]
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:523)[4:org.ops4j.pax.url.mvn:2.4.5]
        at org.ops4j.pax.url.mvn.internal.Connection.getInputStream(Connection.java:123)[4:org.ops4j.pax.url.mvn:2.4.5]
        at java.net.URL.openStream(URL.java:1038)[:1.8.0_65]
        at org.apache.karaf.features.internal.service.RepositoryImpl.load(RepositoryImpl.java:91)[9:org.apache.karaf.features.core:4.0.4]
        ... 11 more
01:17:47.285 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-package-standard': No matching features for openhab-package-standard/0.0.0
01:17:47.296 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-knx': No matching features for openhab-binding-knx/0.0.0
01:17:47.304 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-astro': No matching features for openhab-binding-astro/0.0.0
01:17:47.313 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-ntp': No matching features for openhab-binding-ntp/0.0.0
01:17:47.321 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-zwave': No matching features for openhab-binding-zwave/0.0.0
01:17:47.330 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-http': No matching features for openhab-binding-http/0.0.0
01:17:47.337 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-ui-basic': No matching features for openhab-ui-basic/0.0.0
01:17:47.347 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-ui-paper': No matching features for openhab-ui-paper/0.0.0
01:17:47.356 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-ui-classic': No matching features for openhab-ui-classic/0.0.0
01:17:47.364 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-persistence-rrd4j': No matching features for openhab-persistence-rrd4j/0.0.0
01:17:47.372 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-persistence-jdbc-mariadb': No matching features for openhab-persistence-jdbc-mariadb/0.0.0
01:17:56.642 [INFO ] [marthome.event.ItemStateChangedEvent] - ntp_ntp_local_dateTime changed from 2016-10-08T01:16:56.615+0200 to 2016-10-08T01:17:56.615+0200
01:18:06.229 [ERROR] [st.core.extensions.ExtensionResource] - Exception while installing extension: org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-misc-ruleengine; type=karaf.feature; version="[2.0.0.SNAPSHOT,2.0.0.SNAPSHOT]"; filter:="(&(osgi.identity=openhab-misc-ruleengine)(type=karaf.feature)(version>=2.0.0.SNAPSHOT)(version<=2.0.0.SNAPSHOT))" [caused by: Unable to resolve openhab-misc-ruleengine/2.0.0.SNAPSHOT: missing requirement [openhab-misc-ruleengine/2.0.0.SNAPSHOT] osgi.identity; osgi.identity=openhab-runtime-base; type=karaf.feature]
01:18:06.246 [INFO ] [smarthome.event.ExtensionEvent      ] - misc-ruleengine: org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-misc-ruleengine; type=karaf.feature; version="[2.0.0.SNAPSHOT,2.0.0.SNAPSHOT]"; filter:="(&(osgi.identity=openhab-misc-ruleengine)(type=karaf.feature)(version>=2.0.0.SNAPSHOT)(version<=2.0.0.SNAPSHOT))" [caused by: Unable to resolve openhab-misc-ruleengine/2.0.0.SNAPSHOT: missing requirement [openhab-misc-ruleengine/2.0.0.SNAPSHOT] osgi.identity; osgi.identity=openhab-runtime-base; type=karaf.feature]`

**Comment by kaikreuzer** [comment]
"2.0.0.b3" does not sound as if you have installed a latest snapshot - it looks like something in your setup is mixed up.

**Comment by SuperOok** [comment]
Ok, I did a vanilla install or my Raspbian from scratch. Now it works. Must have been some messing up with older versions...

**Comment by kaikreuzer** [comment]
thanks for the update, glad that it's working!
