### ISSUE TITLE
Failed to build the openhab-distro

### ISSUE THREAD

**Issue by mcloarec** [openhab/openhab-distro#293]
I'm trying to build the distro
I get this error : 

[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building openHAB Feature Verification 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- karaf-maven-plugin:4.0.4:verify (verify) @ openhab-verify ---
[INFO] Using repositories: https://repo.eclipse.org/content/repositories/releases/@id=eclipse-releases,https://repo.eclipse.org/content/repositories/snapshots/@id=eclipse-snapshots@noreleases@snapshots,https://jcenter.bintray.com/@id=jcenter,https://dl.bintray.com/openhab/mvn/@id=openhab-bintray,http://oss.jfrog.org/libs-snapshot/@id=jfrog@noreleases@snapshots,https://dl.bintray.com/maggu2810/maven@id=shk-bintray,http://svn.apache.org/repos/asf/servicemix/m2-repo@id=apache.servicemix.m2,http://repository.springsource.com/maven/bundles/release@id=zodiac-repository,http://repository.springsource.com/maven/bundles/external@id=spring-ebr-repository,https://oss.sonatype.org/content/repositories/ops4j-snapshots/@id=ops4j.sonatype.snapshots.deploy@noreleases@snapshots,https://repository.apache.org/content/groups/snapshots-group@id=apache.snapshots.deploy@noreleases@snapshots,https://repo.maven.apache.org/maven2@id=central
[WARNING] Error resolving artifactorg.ops4j.pax.web:pax-web-features:xml:features:4.2.4:Could not transfer artifact org.ops4j.pax.web:pax-web-features:xml:features:4.2.4 from/to eclipse-releases (https://repo.eclipse.org/content/repositories/releases/): Connect to repo.eclipse.org:443 [repo.eclipse.org/198.41.30.233] failed: Connexion terminée par expiration du délai d'attente
shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.ops4j.pax.web:pax-web-features:xml:features:4.2.4 from/to eclipse-releases (https://repo.eclipse.org/content/repositories/releases/): Connect to repo.eclipse.org:443 [repo.eclipse.org/198.41.30.233] failed: Connexion terminée par expiration du délai d'attente
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:615)
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:570)
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:548)
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:523)
	at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:34)
	at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: shaded.org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.ops4j.pax.web:pax-web-features:xml:features:4.2.4 from/to eclipse-releases (https://repo.eclipse.org/content/repositories/releases/): Connect to repo.eclipse.org:443 [repo.eclipse.org/198.41.30.233] failed: Connexion terminée par expiration du délai d'attente
	at shaded.org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
	at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at shaded.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 16 more
Caused by: shaded.org.apache.maven.wagon.TransferFailedException: Connect to repo.eclipse.org:443 [repo.eclipse.org/198.41.30.233] failed: Connexion terminée par expiration du délai d'attente
	at shaded.org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1085)
	at shaded.org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:977)
	at shaded.org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
	at shaded.org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
	at shaded.org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
	at shaded.org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:560)
	at shaded.org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
	at shaded.org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:404)
	at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
	at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	... 21 more
Caused by: shaded.org.apache.http.conn.HttpHostConnectException: Connect to repo.eclipse.org:443 [repo.eclipse.org/198.41.30.233] failed: Connexion terminée par expiration du délai d'attente
	at shaded.org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:140)
	at shaded.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
	at shaded.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at shaded.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at shaded.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at shaded.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at shaded.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at shaded.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.ops4j.pax.url.mvn.internal.wagon.ConfigurableHttpWagon.execute(ConfigurableHttpWagon.java:142)
	at shaded.org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1000)
	... 30 more
Caused by: java.net.ConnectException: Connexion terminée par expiration du délai d'attente
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at shaded.org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:239)
	at shaded.org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:123)
	... 40 more
[WARNING] Error resolving artifactorg.apache.karaf.features:framework:xml:features:4.0.4:Could not transfer artifact org.apache.karaf.features:framework:xml:features:4.0.4 from/to eclipse-releases (https://repo.eclipse.org/content/repositories/releases/): Connect to repo.eclipse.org:443 [repo.eclipse.org/198.41.30.233] failed: Connexion terminée par expiration du délai d'attente
shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.apache.karaf.features:framework:xml:features:4.0.4 from/to eclipse-releases (https://repo.eclipse.org/content/repositories/releases/): Connect to repo.eclipse.org:443 [repo.eclipse.org/198.41.30.233] failed: Connexion terminée par expiration du délai d'attente
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:615)
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:570)
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:548)
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:523)
	at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:34)
	at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: shaded.org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.apache.karaf.features:framework:xml:features:4.0.4 from/to eclipse-releases (https://repo.eclipse.org/content/repositories/releases/): Connect to repo.eclipse.org:443 [repo.eclipse.org/198.41.30.233] failed: Connexion terminée par expiration du délai d'attente
	at shaded.org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
	at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at shaded.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 16 more
Caused by: shaded.org.apache.maven.wagon.TransferFailedException: Connect to repo.eclipse.org:443 [repo.eclipse.org/198.41.30.233] failed: Connexion terminée par expiration du délai d'attente
	at shaded.org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1085)
	at shaded.org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:977)
	at shaded.org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
	at shaded.org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
	at shaded.org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
	at shaded.org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:560)
	at shaded.org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
	at shaded.org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:404)
	at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
	at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	... 21 more
Caused by: shaded.org.apache.http.conn.HttpHostConnectException: Connect to repo.eclipse.org:443 [repo.eclipse.org/198.41.30.233] failed: Connexion terminée par expiration du délai d'attente
	at shaded.org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:140)
	at shaded.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
	at shaded.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at shaded.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at shaded.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at shaded.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at shaded.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at shaded.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.ops4j.pax.url.mvn.internal.wagon.ConfigurableHttpWagon.execute(ConfigurableHttpWagon.java:142)
	at shaded.org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1000)
	... 30 more
Caused by: java.net.ConnectException: Connexion terminée par expiration du délai d'attente
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at shaded.org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:239)
	at shaded.org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:123)
	... 40 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] openHAB Distribution ............................... SUCCESS [  0.221 s]
[INFO] openHAB Features ................................... SUCCESS [  0.023 s]
[INFO] openHAB Demo Feature Resources ..................... SUCCESS [  0.414 s]
[INFO] openHAB Demo Feature ............................... SUCCESS [  0.802 s]
[INFO] openHAB Feature Aggregate XML ...................... SUCCESS [  0.453 s]
[INFO] openHAB Feature Aggregate KAR ...................... SUCCESS [  8.356 s]
[INFO] openHAB Experimental Feature Addons ................ SUCCESS [  0.092 s]
[INFO] openHAB Feature Verification ....................... FAILURE [16:59 min]
[INFO] openHAB Distributions .............................. SKIPPED
[INFO] openHAB Offline Distribution ....................... SKIPPED
[INFO] openHAB Online Distribution ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17:12 min
[INFO] Finished at: 2016-10-11T09:48:20+02:00
[INFO] Final Memory: 25M/554M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.0.4:verify (verify) on project openhab-verify: Unable to load features descriptors: Error -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :openhab-verify

**Comment by kaikreuzer** [comment]
> Connect to repo.eclipse.org:443 [repo.eclipse.org/198.41.30.233] failed

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=502356, these are temporary issues (not on our end).
Please try the build again a bit later.
