### ISSUE TITLE
Installing openhab2 snapshot from repository onraspberry pi fails

### ISSUE THREAD

**Issue by mihalski** [openhab/openhab-distro#301]
Hi,

I am having a look at openhab due to it's zwave support and homebridge bindings (thus allowing motion sensor integration with homekit). Having followed the instructions on installing openhab2 on a raspbeery pi I encountered the following error:

```
pi@homepi:~ $ sudo apt-get install openhab2-online
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  openhab2-online
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/48.7 MB of archives.
After this operation, 54.8 MB of additional disk space will be used.
(Reading database ... 37653 files and directories currently installed.)
Preparing to unpack .../openhab2-online_2.0.0~20161017033125_all.deb ...
dpkg: error processing archive /var/cache/apt/archives/openhab2-online_2.0.0~20161017033125_all.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
Errors were encountered while processing:
 /var/cache/apt/archives/openhab2-online_2.0.0~20161017033125_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

It appears that there is a problem with the pre-installation script, but I am unable to identify it. Here is what is currently in the script:

```
#!/bin/sh

set -e

UD_CACHE=/var/lib/openhab2/cache
UD_TMP=/var/lib/openhab2/tmp

removeCache(){
    [ -d ${UD_CACHE} ] && rm -rf ${UD_CACHE}
    [ -d ${UD_TMP} ] && rm -rf ${UD_TMP}
}

case "$1" in
        install)
        removeCache
                OH_USER=openhab
                OH_GROUP=openhab
                if [ x"${USER_AND_GROUP}" != x ]; then
                        OH_USER=`echo ${USER_AND_GROUP} | cut -d ":" -f 1`
                        OH_GROUP=`echo ${USER_AND_GROUP} | cut -d ":" -f 2`
                fi
                if ! getent group "$OH_GROUP" > /dev/null 2>&1 ; then
                        addgroup --system "$OH_GROUP" --quiet
                fi
                if ! getent passwd "$OH_USER" > /dev/null 2>&1 ; then
                        adduser --quiet --system --ingroup "$OH_GROUP" --no-create-home \
                        --disabled-password --shell /bin/false \
                        --gecos "openhab2 runtime user" --home /var/lib/openhab2 "$OH_USER"
                fi
                ;;
esac
```

I am running a current version of raspbian on a raspberry pi 3 with all the latest updates and have followed the instructions as stated above.

Regards,
Michal

P.S. It was suggested I tag @theoweiss

**Comment by moeskerv** [comment]
Same here seen with offline package:

 /var/cache/apt/archives/openhab2-offline_2.0.0~20161017033125_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by theoweiss** [comment]
I can confirm this bug. Digging into details...

**Comment by moeskerv** [comment]
Seems that commit https://github.com/openhab/openhab-distro/commit/661c52f171b9e42b8418e6caa71183d073fb342f has to do with this.

**Comment by theoweiss** [comment]
got it. 
Test build is running...

**Comment by theoweiss** [comment]
Installation worked.
Testing the upgrade...

**Comment by moeskerv** [comment]
👍

**Comment by theoweiss** [comment]
Update worked.
From now on "set -e" is on top of my blacklist :-(
Opening PR...

**Comment by theoweiss** [comment]
Hopefully I got it.
Waiting for @kaikreuzer to merge the PR...

**Comment by mihalski** [comment]
Any ETA on when the merge and update of the repository might go through?

**Comment by kaikreuzer** [comment]
Simply look at https://github.com/openhab/openhab-distro/pull/302

**Comment by mihalski** [comment]
I just ran the following command before trying to install again:

`sudo mkdir -p /var/lib/openhab2/tmp`

It seems to have been effective. Was this a reasonable solution?

**Comment by maggu2810** [comment]
It currently fails if the directories do no exist.
So it is okay for a workaround to create the directories before.

**Comment by mihalski** [comment]
I'm going to guess that something was wrong with my solution as:

`sudo /bin/systemctl start openhab2.service`

results in:

```
Oct 19 19:27:28 homepi systemd[1]: Starting openHAB 2 - empowering the smart home...
Oct 19 19:27:28 homepi systemd[1]: Started openHAB 2 - empowering the smart home.
Oct 19 19:27:28 homepi start.sh[24188]: Launching the openHAB runtime...
Oct 19 19:27:30 homepi start.sh[24188]: !SESSION 2016-10-19 19:27:30.799 -----------------------------------------------
Oct 19 19:27:30 homepi start.sh[24188]: eclipse.buildId=unknown
Oct 19 19:27:30 homepi start.sh[24188]: java.version=1.8.0_65
Oct 19 19:27:30 homepi start.sh[24188]: java.vendor=Oracle Corporation
Oct 19 19:27:30 homepi start.sh[24188]: BootLoader constants: OS=linux, ARCH=arm, WS=gtk, NL=en_GB
Oct 19 19:27:30 homepi start.sh[24188]: !ENTRY org.eclipse.osgi 4 0 2016-10-19 19:27:30.800
Oct 19 19:27:30 homepi start.sh[24188]: !MESSAGE Error reading configuration: Unable to create lock manager.
Oct 19 19:27:30 homepi start.sh[24188]: !STACK 0
Oct 19 19:27:30 homepi start.sh[24188]: java.io.IOException: Unable to create lock manager.
Oct 19 19:27:30 homepi start.sh[24188]: at org.eclipse.osgi.storagemanager.StorageManager.open(StorageManager.java:698)
Oct 19 19:27:30 homepi start.sh[24188]: at org.eclipse.osgi.storage.Storage.getChildStorageManager(Storage.java:1749)
Oct 19 19:27:30 homepi start.sh[24188]: at org.eclipse.osgi.storage.Storage.getInfoInputStream(Storage.java:1766)
Oct 19 19:27:30 homepi start.sh[24188]: at org.eclipse.osgi.storage.Storage.<init>(Storage.java:126)
Oct 19 19:27:30 homepi start.sh[24188]: at org.eclipse.osgi.storage.Storage.createStorage(Storage.java:85)
Oct 19 19:27:30 homepi start.sh[24188]: at org.eclipse.osgi.internal.framework.EquinoxContainer.<init>(EquinoxContainer.java:75)
Oct 19 19:27:30 homepi start.sh[24188]: at org.eclipse.osgi.launch.Equinox.<init>(Equinox.java:31)
Oct 19 19:27:30 homepi start.sh[24188]: at org.eclipse.osgi.launch.EquinoxFactory.newFramework(EquinoxFactory.java:24)
Oct 19 19:27:30 homepi start.sh[24188]: at org.apache.karaf.main.Main.launch(Main.java:250)
Oct 19 19:27:30 homepi start.sh[24188]: at org.apache.karaf.main.Main.main(Main.java:175)
Oct 19 19:27:30 homepi systemd[1]: openhab2.service: main process exited, code=exited, status=255/n/a
Oct 19 19:27:31 homepi stop[24314]: stop: Ignoring predefined value for KARAF_HOME
Oct 19 19:27:31 homepi stop[24314]: mkdir: cannot create directory ‘/var/lib/openhab2/log’: Permission denied
Oct 19 19:27:32 homepi stop[24314]: /var/lib/openhab2/port shutdown port file doesn't exist. The container is not running.
Oct 19 19:27:32 homepi systemd[1]: openhab2.service: control process exited, code=exited status=3
Oct 19 19:27:32 homepi systemd[1]: Unit openhab2.service entered failed state.
Oct 19 19:27:32 homepi systemd[1]: openhab2.service holdoff time over, scheduling restart.
Oct 19 19:27:32 homepi systemd[1]: Stopping openHAB 2 - empowering the smart home...
Oct 19 19:27:32 homepi systemd[1]: Starting openHAB 2 - empowering the smart home...
Oct 19 19:27:32 homepi systemd[1]: Started openHAB 2 - empowering the smart home.
Oct 19 19:27:32 homepi start.sh[24462]: Launching the openHAB runtime...
Oct 19 19:27:35 homepi start.sh[24462]: !SESSION 2016-10-19 19:27:35.381 -----------------------------------------------
```

Ad infinitum.

**Comment by maggu2810** [comment]
Are you sure that the ownership of all directories is correct.
I can't help you as I don't use an dpkg based Linux distribution.

**Comment by mihalski** [comment]
Yep.

So originally I should have done:

```
sudo mkdir -p /var/lib/openhab2/tmp
sudo apt-get install openhab2-online
sudo chown openhab.openhab /var/lib/openhab2
```

Et voila! It launches (or at least is still launching).

**Comment by BClark09** [comment]
The initial problem should be resolved already, am I right @theoweiss?

**Comment by theoweiss** [comment]
Yes it's solved.
