### ISSUE TITLE
onewire 1.9 last snapshoot

### ISSUE THREAD

**Issue by Bl00d-B0b** [openhab/openhab-distro#351]
Hello,

Seems onewire does not work. plugin installed, configured (remotely, not localhost) but in log I see unexpected errors:

2016-12-10 20:34:14.001 [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.cm.ManagedService, org.osgi.service.event.EventHandler, id=282, bundle=191/mvn:org.openhab.binding/org.openhab.binding.onewire/1.9.0-SNAPSHOT]: Unexpected problem updating configuration org.openhab.onewire
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
        at org.openhab.binding.onewire.internal.OneWireBinding.updated(OneWireBinding.java:98)[191:org.openhab.binding.onewire:1.9.0.201612090210]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[7:org.apache.felix.configadmin:1.8.8]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[7:org.apache.felix.configadmin:1.8.8]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[7:org.apache.felix.configadmin:1.8.8]
        at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1444)[7:org.apache.felix.configadmin:1.8.8]
        at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1400)[7:org.apache.felix.configadmin:1.8.8]
        at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:143)[7:org.apache.felix.configadmin:1.8.8]
        at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:110)[7:org.apache.felix.configadmin:1.8.8]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]

**Comment by kaikreuzer** [comment]
Please report at https://github.com/openhab/openhab/issues as this is where the binding code is maintained. Thanks!

**Comment by watou** [comment]
@kaikreuzer Should 1.x add-ons receive Booleans like [here](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/OneWireBinding.java#L98)?  Any idea what caused that?

**Comment by Bl00d-B0b** [comment]
Hellio.

I dont know... but i can give ssh access, if someone want to try. i spend 1
week and cant manage one wire to work.

One wire is on raspberry and working ok. and openhab on debian. openhab
other plugims work but onewire i cant manage to run

Ed

2016-12-11 02:54 AM "John Cocula" <notifications@github.com> rašė:

**Comment by kaikreuzer** [comment]
> @kaikreuzer Should 1.x add-ons receive Booleans like here? Any idea what caused that?

Yes, configurations in ConfigAdmin can potentially be stored in any primitive type. So while in OH1, the "normal" way of defining a configuration was through openhab.cfg and its parser always only created the values as strings, you could have also set booleans in ConfigAdmin (e.g. through the console) and this would have caused the same exception. In OH2, when using the Paper UI for configuration changes, the correct primitive type is chosen (that is, the one that is defined in the config.xml).

So the clean solution is to always do an instanceof check (or use a `toString()` on the value) before further processing.

**Comment by watou** [comment]
The number of 1.x addons that assume String or null only, oh my...

**Comment by kaikreuzer** [comment]
It should be fixed for at least the ones that come with a config.xml for the Paper UI. The `toString()` fix is probably quite easy to apply.

**Comment by watou** [comment]
Agreed, but lots of little cleanup jobs ahead. :-/

**Comment by Bl00d-B0b** [comment]
Hello,

Can I fix it myself? or what setting I need to put to config.xml. I'll try
manually to make changes in onewire.cfg file, but it's does not help.
I see in inbox onewire plugin, but when I click inside, it's empty, and a
lot of logs are generated...

P.S. I can give remote access to my onewire gateway, for testing with
several temperature sensors.

Ed

**Comment by watou** [comment]
@Bl00d-B0b I submitted a PR https://github.com/openhab/openhab/pull/4889 that should correct the casting errors in the OneWire binding.  Once it's merged and part of an OH2 build, please try again.  If it's still a problem, open an issue [here](https://github.com/openhab/openhab/issues) as Kai mentioned. In the meantime, you could possibly delete your binding configuration (see `openhab> config help`) and use the .cfg file only (no config via Paper UI until said build).

**Comment by Bl00d-B0b** [comment]
Thanks John for quick fix.

When I can text this fix? when it's merged and be part of OH2 build?

Edward

**Comment by kaikreuzer** [comment]
@Bl00d-B0b Distro 641 already contains this fix!
