### ISSUE TITLE
Package SHA256 algorithm to enable encryption of user password

### ISSUE THREAD

**Issue by EliasGabrielsson** [openhab/openhab-distro#361]
## Goal:
Enable encryption of karaf users passwords according to [documentation](https://karaf.apache.org/manual/latest/security). Karaf already have a package implemented I guess. Today all user passwords are stored in clear text in `etc/users.properties` file.

## Problem:
Openhab2 does currently NOT include a package for SHA256 calculations which Karaf could use.
Errorlog: 
```
2016-12-23 19:45:51.671 [ERROR] [s.modules.encryption.BasicEncryption] - Initialization failed. Digest algorithm SHA256 is not available.
java.security.NoSuchAlgorithmException: SHA256 MessageDigest not available
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)[:1.8.0_111]
	at java.security.Security.getImpl(Security.java:695)[:1.8.0_111]
	at java.security.MessageDigest.getInstance(MessageDigest.java:167)[:1.8.0_111]
	at org.apache.karaf.jaas.modules.encryption.BasicEncryption.<init>(BasicEncryption.java:51)
	at org.apache.karaf.jaas.modules.encryption.BasicEncryptionService.createEncryption(BasicEncryptionService.java:25)
...
```
## Solution:
Add package in the release to solve above problem and verify the solution according to above documentation.

**Comment by abedwardsw** [comment]
should it be SHA-256 instead of SHA256 ?

http://stackoverflow.com/questions/12642742/exception-when-calling-messagedigest-getinstancesha256

**Comment by EliasGabrielsson** [comment]
observant, I'll test it tomorrow. Looks like a reasonable error.

**Comment by EliasGabrielsson** [comment]
Above solution solves the problem.
