### ISSUE TITLE
Custom addons failed on first start of openhab

### ISSUE THREAD

**Issue by presidentio** [openhab/openhab-distro#428]
I start openhab via docker compose. Here is my docker-compose.yml
```yaml
openhab:
  container_name: openhab
  image: "openhab/openhab:2.1.0-snapshot-amd64"
  restart: always
  net: host
  volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "/etc/timezone:/etc/timezone:ro"
    - "./addons:/openhab/addons"
    - "./conf:/openhab/conf"
    - "./userdata:/openhab/userdata"
  environment:
    OPENHAB_HTTP_PORT: "8222"
    OPENHAB_HTTPS_PORT: "8443"
```
Also I have my custom binding with the following MANIFEST.MF
```
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: SmartBox Binding
Bundle-SymbolicName: smartbox-binding;singleton:=true
Bundle-Vendor: openHAB
Bundle-Version: 2.0.0.qualifier
Bundle-RequiredExecutionEnvironment: JavaSE-1.8
Bundle-ClassPath: .,
    lib/retrofit-2.1.0.jar,
    lib/okio-1.8.0.jar,
    lib/okhttp-3.3.0.jar,
    lib/converter-jackson-2.1.0.jar,
    lib/jackson-annotations-2.7.0.jar,
    lib/jackson-core-2.7.2.jar,
    lib/jackson-databind-2.7.2.jar
Import-Package: 
 org.eclipse.smarthome.config.core,
 org.eclipse.smarthome.config.discovery,
 org.eclipse.smarthome.core.library.types,
 org.eclipse.smarthome.core.thing,
 org.eclipse.smarthome.core.thing.binding,
 org.eclipse.smarthome.core.thing.binding.builder,
 org.eclipse.smarthome.core.thing.type,
 org.eclipse.smarthome.core.types,
 org.slf4j,
 org.osgi.framework,
 com.google.common.base,
 com.google.common.collect,
 org.apache.commons.lang,
 org.apache.commons.io
Service-Component: OSGI-INF/*.xml
Export-Package: com.presidentio.openhab.binding.smartbox
```

I put my binding to the *./addons* directory. After the first start of my docker container using `docker-compose up -d` and package selection (Standard, Expert, etc.) I don't see my binding on the UI. I see error message in the log:
```
14:30:37.997 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/openhab/addons/smartbox-binding-1.0.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: smartbox-binding [10]
  Unresolved requirement: Import-Package: org.eclipse.smarthome.config.core

	at org.eclipse.osgi.container.Module.start(Module.java:434)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:392)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1253)[4:org.apache.felix.fileinstall:3.5.6]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1225)[4:org.apache.felix.fileinstall:3.5.6]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:512)[4:org.apache.felix.fileinstall:3.5.6]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361)[4:org.apache.felix.fileinstall:3.5.6]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:312)[4:org.apache.felix.fileinstall:3.5.6]
```

But after the restart of the docker container using commands:
```
docker stop openhab
docker start openhab
```
my binding starts working well and I don't see this error message.

**Comment by kaikreuzer** [comment]
Would be great if you could try to reproduce it with the plain zip distribution of openHAB, just to rule out that this is anything specific to Docker.

**Comment by presidentio** [comment]
I've tested with latest docker image and latest zip archive. Zip archive - works well, Docker - problem still exists

**Comment by kaikreuzer** [comment]
Thanks for testing - so in that case, I would very much suggest to report the issue here: https://github.com/openhab/openhab-docker
