### ISSUE TITLE
Oh2 errors in console

### ISSUE THREAD

**Issue by big-col** [openhab/openhab-distro#435]
Hi,  guys, I've just noticed these errors in the OH2 console but i can't see any corresponding errors in the log files.

openhab> /jni/win/x86_64/jd2xx.dll
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:213)
at org.eclipse.jetty.server.HttpInputOverHTTP.blockForContent(HttpInputOverHTTP.java:66)
at org.eclipse.jetty.server.HttpInput$1.waitForContent(HttpInput.java:489)
at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:122)
at java.io.InputStream.read(Unknown Source)
at org.jupnp.util.io.IO.copyLarge(IO.java:969)
at org.jupnp.util.io.IO.copy(IO.java:943)
at org.jupnp.util.io.IO.toByteArray(IO.java:391)
at org.jupnp.util.io.IO.readBytes(IO.java:110)
at org.jupnp.transport.impl.ServletUpnpStream.readRequestMessage(ServletUpnpStream.java:137)
at org.jupnp.transport.impl.ServletUpnpStream.run(ServletUpnpStream.java:61)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:161)
at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
... 3 more
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:213)
at org.eclipse.jetty.server.HttpInputOverHTTP.blockForContent(HttpInputOverHTTP.java:66)
at org.eclipse.jetty.server.HttpInput$1.waitForContent(HttpInput.java:489)
at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:122)
at java.io.InputStream.read(Unknown Source)
at org.jupnp.util.io.IO.copyLarge(IO.java:969)
at org.jupnp.util.io.IO.copy(IO.java:943)
at org.jupnp.util.io.IO.toByteArray(IO.java:391)
at org.jupnp.util.io.IO.readBytes(IO.java:110)
at org.jupnp.transport.impl.ServletUpnpStream.readRequestMessage(ServletUpnpStream.java:137)
at org.jupnp.transport.impl.ServletUpnpStream.run(ServletUpnpStream.java:61)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:161)
at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
... 3 more

**Comment by kaikreuzer** [comment]
jd2xx.dll is some native library from USB/serial access - I have no clue how this can be related in any way to upnp and I have also never ever seen such an error.
The exception itself sounds as if some upnp device in your network might not have been responded correctly - so unless you find a real problem within openHAB that is related to this log, I would suggest to close the issue.
You might want to report it at https://github.com/jupnp/jupnp/issues to have the logging improved (and no exception been printed to system out....)
