### ISSUE TITLE
openhab2 initial install fails on FreeBSD

### ISSUE THREAD

**Issue by rajil** [openhab/openhab-distro#470]
Hello,

It tried to run openhab2 on FreeBSD-11 and it failed with a bunch of messages. The system has openjdk8-8.131.11 installed and openhab1 works fine on it.

```

[ERROR] [ficate.internal.CertificateGenerator] - Failed to generate a new SSL Certificate.
java.security.cert.CertificateException: Failed to generate the new certificate.
        at org.openhab.io.jetty.certificate.internal.CertificateGenerator.generateCertificate(CertificateGenerator.java:202)[168:org.openhab.io.jetty.certificate:2.0.0]
        at org.openhab.io.jetty.certificate.internal.CertificateGenerator.start(CertificateGenerator.java:84)[168:org.openhab.io.jetty.certificate:2.0.0]
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at java.security.AccessController.doPrivileged(Native Method)[:1.8.0_131]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:941)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:318)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.Module.doStart(Module.java:571)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.Module.start(Module.java:439)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:392)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:411)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1287)[8:org.apache.karaf.features.core:4.0.8]
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:860)[8:org.apache.karaf.features.core:4.0.8]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1176)[8:org.apache.karaf.features.core:4.0.8]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1074)[8:org.apache.karaf.features.core:4.0.8]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]
Caused by: java.security.NoSuchAlgorithmException: EC KeyPairGenerator not available
        at java.security.KeyPairGenerator.getInstance(KeyPairGenerator.java:218)[:1.8.0_131]
        at org.openhab.io.jetty.certificate.internal.CertificateGenerator.generateCertificate(CertificateGenerator.java:159)[168:org.openhab.io.jetty.certificate:2.0.0]
        ... 20 more
2017-06-24 14:30:21.346 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at /start
2017-06-24 14:30:21.774 [WARN ] [org.apache.karaf.shell.ssh.SshUtils ] - Configured cipher 'aes128-ctr' not available
2017-06-24 14:30:21.775 [WARN ] [org.apache.karaf.shell.ssh.SshUtils ] - Configured cipher 'arcfour128' not available
2017-06-24 14:30:21.775 [WARN ] [org.apache.karaf.shell.ssh.SshUtils ] - Configured cipher 'aes128-cbc' not available
2017-06-24 14:30:21.775 [WARN ] [org.apache.karaf.shell.ssh.SshUtils ] - Configured cipher '3des-cbc' not available
2017-06-24 14:30:21.776 [WARN ] [org.apache.karaf.shell.ssh.SshUtils ] - Configured cipher 'blowfish-cbc' not available
2017-06-24 14:30:21.777 [WARN ] [org.apache.karaf.shell.ssh.SshUtils ] - Configured keyexchange 'ecdh-sha2-nistp521' not available
2017-06-24 14:30:21.777 [WARN ] [org.apache.karaf.shell.ssh.SshUtils ] - Configured keyexchange 'ecdh-sha2-nistp384' not available
2017-06-24 14:30:21.777 [WARN ] [org.apache.karaf.shell.ssh.SshUtils ] - Configured keyexchange 'ecdh-sha2-nistp256' not available
```

**Comment by BClark09** [comment]
Hi @rajil, have you tried with another version of Java? I know there have been problems with openjdk and certificates in the past.

**Comment by rajil** [comment]
I tried openjdk-7 and had the same issue.

**Comment by BClark09** [comment]
I mean, have you tried installing oracle java 8 and using that?

**Comment by rajil** [comment]
Unfortunately, oracle java ([https://www.freshports.org/java/linux-oracle-jdk18/]) requires a linux compatibility layer to be setup.  I am trying to run openhab in FreeBSD jail, which will not have access to the linux layer.
The cleanest solution would to have openjdk working with openhab2.

**Comment by BClark09** [comment]
The following web resource may be able to help you here: http://armoredbarista.blogspot.co.uk/2013/10/how-to-use-ecc-with-openjdk.html

**Comment by rajil** [comment]
I disabled the algorithms, but that didnt seem to help.

```
# tail -f  /usr/local/openjdk8/jre/lib/security/java.security
#
# The builtin DGC filter can approximately be represented as the filter pattern:
#
#sun.rmi.transport.dgcFilter=\
#    java.rmi.server.ObjID;\
#    java.rmi.server.UID;\
#    java.rmi.dgc.VMID;\
#    java.rmi.dgc.Lease;\
#    maxdepth=5;maxarray=10000
jdk.tls.disabledAlgorithms=EC,ECDHE,ECDH
```
And the log file says
```
2017-07-08 21:50:23.345 [ERROR] [ficate.internal.CertificateGenerator] - Failed to generate a new SSL Certificate.
java.security.cert.CertificateException: Failed to generate the new certificate.
        at org.openhab.io.jetty.certificate.internal.CertificateGenerator.generateCertificate(CertificateGenerator.java:202)[168:org.openhab.io.jetty.certificate:2.0.0]
        at org.openhab.io.jetty.certificate.internal.CertificateGenerator.start(CertificateGenerator.java:84)[168:org.openhab.io.jetty.certificate:2.0.0]
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at java.security.AccessController.doPrivileged(Native Method)[:1.8.0_131]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:941)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:318)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.Module.doStart(Module.java:571)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.Module.start(Module.java:439)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:392)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:411)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1287)[8:org.apache.karaf.features.core:4.0.8]
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:860)[8:org.apache.karaf.features.core:4.0.8]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1176)[8:org.apache.karaf.features.core:4.0.8]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1074)[8:org.apache.karaf.features.core:4.0.8]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]
Caused by: java.security.NoSuchAlgorithmException: EC KeyPairGenerator not available
        at java.security.KeyPairGenerator.getInstance(KeyPairGenerator.java:218)[:1.8.0_131]
        at org.openhab.io.jetty.certificate.internal.CertificateGenerator.generateCertificate(CertificateGenerator.java:159)[168:org.openhab.io.jetty.certificate:2.0.0]
        ... 20 more
2017-07-08 21:50:39.683 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at /start
2017-07-08 21:50:40.925 [WARN ] [org.apache.karaf.shell.ssh.SshUtils ] - Configured cipher 'aes128-ctr' not available
2017-07-08 21:50:40.926 [WARN ] [org.apache.karaf.shell.ssh.SshUtils ] - Configured cipher 'arcfour128' not available
2017-07-08 21:50:40.927 [WARN ] [org.apache.karaf.shell.ssh.SshUtils ] - Configured cipher 'aes128-cbc' not available
2017-07-08 21:50:40.927 [WARN ] [org.apache.karaf.shell.ssh.SshUtils ] - Configured cipher '3des-cbc' not available
2017-07-08 21:50:40.927 [WARN ] [org.apache.karaf.shell.ssh.SshUtils ] - Configured cipher 'blowfish-cbc' not available
2017-07-08 21:50:40.928 [WARN ] [org.apache.karaf.shell.ssh.SshUtils ] - Configured keyexchange 'ecdh-sha2-nistp521' not available
2017-07-08 21:50:40.929 [WARN ] [org.apache.karaf.shell.ssh.SshUtils ] - Configured keyexchange 'ecdh-sha2-nistp384' not available
2017-07-08 21:50:40.929 [WARN ] [org.apache.karaf.shell.ssh.SshUtils ] - Configured keyexchange 'ecdh-sha2-nistp256' not available
2017-07-08 21:51:00.226 [WARN ] [url.mvn.internal.AetherBasedResolver] - Error resolving artifact org.openhab.ui:org.openhab.ui.habpanel:jar:2.0.0: [Could not transfer artifact org.openhab.ui:org.openhab.ui.habpanel:jar:2.0.0 from/to openhab (https://dl.bintray.com/openhab/mvn/online-repo/2.0/): RSA premaster secret error]
java.io.IOException: Error resolving artifact org.openhab.ui:org.openhab.ui.habpanel:jar:2.0.0: [Could not transfer artifact org.openhab.ui:org.openhab.ui.habpanel:jar:2.0.0 from/to openhab (https://dl.bintray.com/openhab/mvn/online-repo/2.0/): RSA premaster secret error]
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:720)[7:org.ops4j.pax.url.mvn:2.5.2]
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:659)[7:org.ops4j.pax.url.mvn:2.5.2]
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:600)[7:org.ops4j.pax.url.mvn:2.5.2]
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:567)[7:org.ops4j.pax.url.mvn:2.5.2]
        at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:36)[8:org.apache.karaf.features.core:4.0.8]
        at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)[8:org.apache.karaf.features.core:4.0.8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]
Caused by: shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact org.openhab.ui:org.openhab.ui.habpanel:jar:2.0.0
        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
        at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:705)[7:org.ops4j.pax.url.mvn:2.5.2]
        ... 12 more
2017-07-08 21:51:00.251 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-ui-habpanel, openhab-misc-ruleengine, openhab-ui-paper': Error

```

**Comment by kaikreuzer** [comment]
Is this still an issue with openHAB 3 and Java 11?
I'd hope not and looking at the age of this issue, I'd suggest to close it.
