### ISSUE TITLE
MQTT not publish or subscribe after update to OH2.1

### ISSUE THREAD

**Issue by vuhams** [openhab/openhab-distro#475]
In an existing OH2.0 setup MQTT is working properly without any issues. but, after i update it to OH2.1, MQTT is not publish or subscribe to any topic.

**Comment by kaikreuzer** [comment]
Please report this as an issue of the MQTT binding at https://github.com/openhab/openhab1-addons/issues, so that it can be analyzed and tracked there.

**Comment by ThomDietrich** [comment]
@vuhams please create the other issue (and link it here).
I've seen the same problems. I was able to regain functionality by uninstalling and reinstalling the binding.

Here are the log messages I was seeing before and after the reinstall:
```
2017-07-01 11:50:31.983 [INFO ] [penhab.io.transport.mqtt.MqttService] - Stopping broker connection 'broker'
2017-07-01 11:52:13.266 [INFO ] [penhab.io.transport.mqtt.MqttService] - MQTT Service initialization completed.
2017-07-01 11:52:13.300 [INFO ] [t.mqtt.internal.MqttBrokerConnection] - Starting MQTT broker connection 'broker'
2017-07-01 11:52:14.332 [ERROR] [penhab.io.transport.mqtt.MqttService] - Error starting broker connection
        at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:79)[218:org.openhab.io.transport.mqtt:1.10.0]
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)[218:org.openhab.io.transport.mqtt:1.10.0]
        at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)[218:org.openhab.io.transport.mqtt:1.10.0]

2017-07-01 12:25:43.081 [INFO ] [penhab.io.transport.mqtt.MqttService] - Stopping broker connection 'broker'
2017-07-01 12:27:24.135 [INFO ] [penhab.io.transport.mqtt.MqttService] - MQTT Service initialization completed.
2017-07-01 12:27:24.138 [INFO ] [t.mqtt.internal.MqttBrokerConnection] - Starting MQTT broker connection 'broker'

```
