### ISSUE TITLE
some openHab bundles doesn't active on Eclipse Smart Home

### ISSUE THREAD

**Issue by amarpulli544** [openhab/openhab-distro#480]
Hello,
I am trying to use openhab1 -bundles and openhab2-bundles into eclipse smart home.
This is smart home repo,   https://github.com/maggu2810/smarthome-packaging-sample-karaf
Here I just clone repo and call   `mvn clean install`, then start the  server.
When I put the jar file of bundle into deploy folder. It showing always bundle status Installed.
see here is my log file:

```
2017-07-05 18:50:19,610 | ERROR | lixDispatchQueue | wemo                             | 204 - org.eclipse.smarthome.binding.wemo - 0.9.0.201707051748 | FrameworkEvent ERROR - org.eclipse.smarthome.binding.wemo
org.osgi.framework.BundleException: Unable to resolve org.eclipse.smarthome.binding.wemo [204](R 204.0): missing requirement [org.eclipse.smarthome.binding.wemo [204](R 204.0)] osgi.wiring.package; (osgi.wiring.package=org.eclipse.smarthome.io.transport.upnp) Unresolved requirements: [[org.eclipse.smarthome.binding.wemo [204](R 204.0)] osgi.wiring.package; (osgi.wiring.package=org.eclipse.smarthome.io.transport.upnp)]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4132) [?:?]
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) [?:?]
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371) [?:?]
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) [?:?]
        at java.lang.Thread.run(Thread.java:745) [?:?]
2017-07-05 18:50:19,614 | ERROR | FelixStartLevel  | Felix                            |  -  -  | Bundle org.eclipse.smarthome.binding.wemo [204] Error starting file:/E:/SmartHome/smarthome-packaging-sample-karaf/target/assembly/deploy/org.eclipse.smarthome.binding.wemo_0.9.0.201707051748.jar (org.osgi.framework.BundleException: Unable to resolve org.eclipse.smarthome.binding.wemo [204](R 204.0): missing requirement [org.eclipse.smarthome.binding.wemo [204](R 204.0)] osgi.wiring.package; (osgi.wiring.package=org.eclipse.smarthome.io.transport.upnp) Unresolved requirements: [[org.eclipse.smarthome.binding.wemo [204](R 204.0)] osgi.wiring.package; (osgi.wiring.package=org.eclipse.smarthome.io.transport.upnp)])
org.osgi.framework.BundleException: Unable to resolve org.eclipse.smarthome.binding.wemo [204](R 204.0): missing requirement [org.eclipse.smarthome.binding.wemo [204](R 204.0)] osgi.wiring.package; (osgi.wiring.package=org.eclipse.smarthome.io.transport.upnp) Unresolved requirements: [[org.eclipse.smarthome.binding.wemo [204](R 204.0)] osgi.wiring.package; (osgi.wiring.package=org.eclipse.smarthome.io.transport.upnp)]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4132) [?:?]
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) [?:?]
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371) [?:?]
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) [?:?]
        at java.lang.Thread.run(Thread.java:745) [?:?]

```
Bundle list:

```
173 | Active    |  80 | 2.9.2.v20160428-1452  | Xbase Model
174 | Active    |  80 | 2.9.2                 | Xbase Runtime Library
191 | Active    |  80 | 2.2.0                 | JUPnP Library
192 | Active    |  80 | 1.9.6                 | MIME streaming extension
193 | Active    |  80 | 1.0.9                 | mapdb
194 | Active    |  80 | 5.0.2                 | Require-Bundle Fix :: org.objectweb.asm
200 | Active    |  80 | 3.1.4                 | Stax2 API
204 | Installed |  80 | 0.9.0.201707051748    | Eclipse SmartHome Wemo Binding
```

Even some eclipse smart home bundles also doesn't work for me. I am trying multiple bundles deployed into my repo, some bundle working fine and some bundle showing status Installed. How I could resolve this issue.
 Is there any stuff add to my pom.xml file?

Thanks ,
Amar.

**Comment by kaikreuzer** [comment]
Please don't do cross-postings across repos, especially if it isn't about openHAB at all.
