### ISSUE TITLE
Problem with denon binding in openhab 2.x

### ISSUE THREAD

**Issue by HaKuNaCH** [openhab/openhab-distro#481]
Hi
The items from the binding are generally working, but I got no feedback when the items are changed on the receiver itself, means the status, e.g. 
Switch		DenonPowerMain			"Power Denon"										<switch>						{ denon = "avr2000#ZM" }
is only changed when I switch it via the openhab GUI or app.

During the startup, I get the following error:
2017-07-12 21:20:34.559 [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.event.EventHandler, org.osgi.service.cm.ManagedService, id=313, bundle=199/mvn:org.openhab.binding/org.openhab.binding.denon/1.11.0-SNAPSHOT]: Unexpected problem updating configuration org.openhab.denon
java.lang.NullPointerException
	at java.math.BigDecimal.compareTo(BigDecimal.java:2625)[:1.8.0_131]
	at org.openhab.core.library.types.PercentType.validateValue(PercentType.java:47)[192:org.openhab.core.compat1x:2.2.0.201707082234]
	at org.openhab.core.library.types.PercentType.<init>(PercentType.java:43)[192:org.openhab.core.compat1x:2.2.0.201707082234]
	at org.openhab.binding.denon.internal.DenonConnector.updateSecondaryZones(DenonConnector.java:470)[199:org.openhab.binding.denon:1.11.0.201707100110]
	at org.openhab.binding.denon.internal.DenonConnector.refreshHttpProperties(DenonConnector.java:517)[199:org.openhab.binding.denon:1.11.0.201707100110]
	at org.openhab.binding.denon.internal.DenonConnector.updateState(DenonConnector.java:214)[199:org.openhab.binding.denon:1.11.0.201707100110]
	at org.openhab.binding.denon.internal.DenonConnector.getInitialState(DenonConnector.java:205)[199:org.openhab.binding.denon:1.11.0.201707100110]
	at org.openhab.binding.denon.internal.DenonConnector.connect(DenonConnector.java:162)[199:org.openhab.binding.denon:1.11.0.201707100110]
	at org.openhab.binding.denon.internal.DenonBinding.updated(DenonBinding.java:201)[199:org.openhab.binding.denon:1.11.0.201707100110]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[3:org.apache.felix.configadmin:1.8.12]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[3:org.apache.felix.configadmin:1.8.12]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[3:org.apache.felix.configadmin:1.8.12]
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1461)[3:org.apache.felix.configadmin:1.8.12]
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1417)[3:org.apache.felix.configadmin:1.8.12]
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:141)[3:org.apache.felix.configadmin:1.8.12]
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:109)[3:org.apache.felix.configadmin:1.8.12]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]
2017-07-12 21:20:34.571 [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.event.EventHandler, org.osgi.service.cm.ManagedService, id=314, bundle=189/mvn:org.openhab.binding/org.openhab.binding.lgtv/1.11.0-SNAPSHOT]: Unexpected problem updating configuration org.openhab.lgtv
java.lang.NullPointerException
	at org.openhab.binding.lgtv.internal.LgtvBinding.updated(LgtvBinding.java:322)[189:org.openhab.binding.lgtv:1.11.0.201707100110]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[3:org.apache.felix.configadmin:1.8.12]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[3:org.apache.felix.configadmin:1.8.12]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[3:org.apache.felix.configadmin:1.8.12]
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1461)[3:org.apache.felix.configadmin:1.8.12]
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1417)[3:org.apache.felix.configadmin:1.8.12]
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:141)[3:org.apache.felix.configadmin:1.8.12]
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:109)[3:org.apache.felix.configadmin:1.8.12]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]

**Comment by kaikreuzer** [comment]
The Denon binding passes a null value to the PercentType constructor, so this is clearly a bug in the binding.
Please hence report it at https://github.com/openhab/openhab1-addons/issues. Thanks!
