### ISSUE TITLE
Exception in SIGWINCH handler

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#564]
With snapshot 1078, a new error is produced at each startup on a RPI:
```
Exception in thread "SIGWINCH handler" java.lang.UnsupportedOperationException
        at org.jline.terminal.impl.NativeSignalHandler.handle(NativeSignalHandler.java:24)
        at org.apache.karaf.shell.impl.console.JLineTerminal.handle(JLineTerminal.java:280)
        at org.jline.terminal.impl.AbstractTerminal.raise(AbstractTerminal.java:65)
        at org.jline.terminal.impl.PosixSysTerminal.lambda$handle$1(PosixSysTerminal.java:65)
        at org.jline.utils.Signals.lambda$register$1(Signals.java:51)
        at com.sun.proxy.$Proxy25.handle(Unknown Source)
        at sun.misc.Signal$1.run(Signal.java:212)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by kaikreuzer** [comment]
I've seen this on older builds as well already. Definitely something to report (and fix) at Karaf as openHAB is not at all involved in that stacktrace.

**Comment by maggu2810** [comment]
It has been already reported and fixed in Karaf. The recent 4.1 and 4.2 releases (WRT the M for 4.2) contains the fix.

**Comment by maggu2810** [comment]
IIRC it's about the jline library that is used by the respective Karaf versions.

**Comment by kaikreuzer** [comment]
> The recent 4.1 and 4.2 releases (WRT the M for 4.2) contains the fix.

As we are now on Karaf 4.1.3, I assume this is fixed now.
