### ISSUE TITLE
resolution of uriFragment failed with NPE

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#614]
First startup of OH snapshot 1140 with the kar file: I got 3 of these errors:
```
2017-12-15 19:57:46.137 [ERROR] [xbase.resource.BatchLinkableResource] - resolution of uriFragment '|::0.2.10.2.0.0.2.0.1.1.0.2.0.6.6::0::/1' failed.
java.lang.NullPointerException: null
        at org.eclipse.xtext.xbase.resource.BatchLinkingService.resolveBatched(BatchLinkingService.java:62) [164:org.eclipse.xtext.xbase:2.12.0.v20170519-0752]
        at org.eclipse.xtext.xbase.resource.BatchLinkingService.resolveBatched(BatchLinkingService.java:41) [164:org.eclipse.xtext.xbase:2.12.0.v20170519-0752]
        at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getEObject(BatchLinkableResource.java:117) [164:org.eclipse.xtext.xbase:2.12.0.v20170519-0752]
        at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223) [71:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:199) [71:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:259) [71:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eResolveProxy(BasicEObjectImpl.java:1477) [71:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.xtext.xbase.impl.XAbstractFeatureCallImplCustom.getFeature(XAbstractFeatureCallImplCustom.java:48) [164:org.eclipse.xtext.xbase:2.12.0.v20170519-0752]
        at org.eclipse.xtext.xbase.util.FeatureCallAsTypeLiteralHelper.getRootTypeLiteral(FeatureCallAsTypeLiteralHelper.java:128) [164:org.eclipse.xtext.xbase:2.12.0.v20170519-0752]
        at org.eclipse.xtext.xbase.imports.TypeUsageCollector.acceptPreferredType(TypeUsageCollector.java:512) [164:org.eclipse.xtext.xbase:2.12.0.v20170519-0752]
        at org.eclipse.xtext.xbase.imports.TypeUsageCollector.collectAllReferences(TypeUsageCollector.java:202) [164:org.eclipse.xtext.xbase:2.12.0.v20170519-0752]
        at org.eclipse.xtext.xbase.imports.TypeUsageCollector.collectTypeUsages(TypeUsageCollector.java:170) [164:org.eclipse.xtext.xbase:2.12.0.v20170519-0752]
        at org.eclipse.xtext.xbase.validation.XbaseValidator.checkImports(XbaseValidator.java:1148) [164:org.eclipse.xtext.xbase:2.12.0.v20170519-0752]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.xtext.validation.AbstractDeclarativeValidator$MethodWrapper.invoke(AbstractDeclarativeValidator.java:118) [160:org.eclipse.xtext:2.12.0.v20170518-0959]
        at org.eclipse.xtext.validation.AbstractDeclarativeValidator.internalValidate(AbstractDeclarativeValidator.java:312) [160:org.eclipse.xtext:2.12.0.v20170518-0959]
        at org.eclipse.xtext.validation.AbstractInjectableValidator.validate(AbstractInjectableValidator.java:71) [160:org.eclipse.xtext:2.12.0.v20170518-0959]
        at org.eclipse.xtext.validation.CompositeEValidator.validate(CompositeEValidator.java:151) [160:org.eclipse.xtext:2.12.0.v20170518-0959]
        at org.eclipse.emf.ecore.util.Diagnostician.doValidate(Diagnostician.java:171) [71:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:158) [71:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137) [71:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:181) [71:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161) [71:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137) [71:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:108) [71:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.validateModel(ModelRepositoryImpl.java:293) [134:org.eclipse.smarthome.model.core:0.10.0.b1]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:97) [134:org.eclipse.smarthome.model.core:0.10.0.b1]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:247) [134:org.eclipse.smarthome.model.core:0.10.0.b1]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.addModelsToRepo(FolderObserver.java:178) [134:org.eclipse.smarthome.model.core:0.10.0.b1]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.activate(FolderObserver.java:122) [134:org.eclipse.smarthome.model.core:0.10.0.b1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.apache.felix.scr.impl.inject.BaseMethod.invokeMethod(BaseMethod.java:229) [42:org.apache.felix.scr:2.0.12]
        at org.apache.felix.scr.impl.inject.BaseMethod.access$500(BaseMethod.java:39) [42:org.apache.felix.scr:2.0.12]
        at org.apache.felix.scr.impl.inject.BaseMethod$Resolved.invoke(BaseMethod.java:650) [42:org.apache.felix.scr:2.0.12]
        at org.apache.felix.scr.impl.inject.BaseMethod.invoke(BaseMethod.java:506) [42:org.apache.felix.scr:2.0.12]
        at org.apache.felix.scr.impl.inject.ActivateMethod.invoke(ActivateMethod.java:307) [42:org.apache.felix.scr:2.0.12]
        at org.apache.felix.scr.impl.inject.ActivateMethod.invoke(ActivateMethod.java:299) [42:org.apache.felix.scr:2.0.12]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:298) [42:org.apache.felix.scr:2.0.12]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:109) [42:org.apache.felix.scr:2.0.12]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:906) [42:org.apache.felix.scr:2.0.12]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:879) [42:org.apache.felix.scr:2.0.12]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:749) [42:org.apache.felix.scr:2.0.12]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:675) [42:org.apache.felix.scr:2.0.12]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:430) [42:org.apache.felix.scr:2.0.12]
        at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.configurationUpdated(ConfigurableComponentHolder.java:431) [42:org.apache.felix.scr:2.0.12]
        at org.apache.felix.scr.impl.manager.RegionConfigurationSupport.configurationEvent(RegionConfigurationSupport.java:284) [42:org.apache.felix.scr:2.0.12]
        at org.apache.felix.scr.impl.manager.RegionConfigurationSupport$1.configurationEvent(RegionConfigurationSupport.java:89) [42:org.apache.felix.scr:2.0.12]
        at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.sendEvent(ConfigurationManager.java:2090) [7:org.apache.felix.configadmin:1.8.16]
        at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.run(ConfigurationManager.java:2058) [7:org.apache.felix.configadmin:1.8.16]
        at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:141) [7:org.apache.felix.configadmin:1.8.16]
        at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:109) [7:org.apache.felix.configadmin:1.8.16]
        at java.lang.Thread.run(Thread.java:745) [?:?]
```

**Comment by kaikreuzer** [comment]
I have that also, but only from time to time - it's nothing new.
We should probably re-open https://github.com/eclipse/smarthome/issues/3335. Could you post on that issue?

**Comment by lolodomo** [comment]
When I restarted, it did not occur a second time.
