### ISSUE TITLE
openhab doesn't start since 2.2: Error installing boot features

### ISSUE THREAD

**Issue by ElmarKnipp** [openhab/openhab-distro#626]
I could not start openhab since I tried to use version 2.2. Same problem with 2.3-SNAPSHOT. 2.1 works great.

Here is the relevant part of the logfile:

```
2017-12-19 08:12:07.365 [WARN ] [org.jline                           ] - Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
2017-12-19 08:12:08.356 [ERROR] [ternal.service.BootFeaturesInstaller] - Error installing boot features
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@4c99da87 rejected from java.util.concurrent.ThreadPoolExecutor@4c7ac665[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379) [?:?]
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) [?:?]
        at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:681) [?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvisionInThread(FeaturesServiceImpl.java:1146) [9:org.apache.karaf.features.core:4.1.3]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installFeatures(FeaturesServiceImpl.java:1022) [9:org.apache.karaf.features.core:4.1.3]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installFeatures(FeaturesServiceImpl.java:915) [9:org.apache.karaf.features.core:4.1.3]
        at org.apache.karaf.features.internal.service.BootFeaturesInstaller.installBootFeatures(BootFeaturesInstaller.java:107) [9:org.apache.karaf.features.core:4.1.3]
        at org.apache.karaf.features.internal.service.BootFeaturesInstaller.start(BootFeaturesInstaller.java:87) [9:org.apache.karaf.features.core:4.1.3]
        at org.apache.karaf.features.internal.osgi.Activator.doStart(Activator.java:273) [9:org.apache.karaf.features.core:4.1.3]
        at org.apache.karaf.util.tracker.BaseActivator.run(BaseActivator.java:242) [9:org.apache.karaf.features.core:4.1.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by ElmarKnipp** [comment]
I am using openhab/openhab:2.2.0-amd64-debian

**Comment by martinvw** [comment]
What docker command do you use? Did you see the docker part in the releasenotes:

> Running openhab using docker
There are small changes for running openHAB using docker. For both docker and docker-compose you have to pass a parameter to inform docker that it should 'allocate a pseudo-TTY'. The examples have been updated but the short explanation is that docker run needs either the -t or --tty parameter and docker-compose needs configuration format 2.1 and tty: true.

**Comment by kaikreuzer** [comment]
This indeed sounds like a docker-related issue, so I would suggest to either first discuss it in the forum or open an issue at https://github.com/openhab/openhab-docker/issues.

**Comment by wborn** [comment]
There's an issue for this, see: https://github.com/openhab/openhab-docker/issues/133

**Comment by netcoding** [comment]
The problem still exists and i don't use Docker.
I've only upgraded to "openhab2 2.2.0-1" on my raspberry.


`
2018-01-13 00:19:51.700 [WARN ] [org.jline                           ] - Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
2018-01-13 00:19:58.184 [ERROR] [ternal.service.BootFeaturesInstaller] - Error installing boot features
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@161e783 rejected from java.util.concurrent.ThreadPoolExecutor@66d36c[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379) [?:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) [?:?]
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:681) [?:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvisionInThread(FeaturesServiceImpl.java:1146) [9:org.apache.karaf.features.core:4.1.3]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installFeatures(FeaturesServiceImpl.java:1022) [9:org.apache.karaf.features.core:4.1.3]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installFeatures(FeaturesServiceImpl.java:915) [9:org.apache.karaf.features.core:4.1.3]
	at org.apache.karaf.features.internal.service.BootFeaturesInstaller.installBootFeatures(BootFeaturesInstaller.java:107) [9:org.apache.karaf.features.core:4.1.3]
	at org.apache.karaf.features.internal.service.BootFeaturesInstaller.start(BootFeaturesInstaller.java:87) [9:org.apache.karaf.features.core:4.1.3]
	at org.apache.karaf.features.internal.osgi.Activator.doStart(Activator.java:273) [9:org.apache.karaf.features.core:4.1.3]
	at org.apache.karaf.util.tracker.BaseActivator.run(BaseActivator.java:242) [9:org.apache.karaf.features.core:4.1.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
`
