### ISSUE TITLE
org.jline - Error creating JNA based terminal: com/sun/jna/Platform

### ISSUE THREAD

**Issue by BasvanH** [openhab/openhab-distro#687]
Hello,

I have upgraded docker image from 1232 to 1263. Left configuration date in place. OH is stuck in a loop and gives the folowing error:

```
2018-04-24 19:46:48.419 [DEBUG] [org.jline                           ] - BundleEvent STARTING - org.jline
2018-04-24 19:46:48.440 [DEBUG] [org.jline                           ] - BundleEvent STARTED - org.jline
2018-04-24 19:46:57.434 [INFO ] [egram.internal.TelegramActionService] - Bot xxx_openhab_bot loaded from config file
2018-04-24 19:46:58.588 [INFO ] [.io.caldav.internal.CalDavLoaderImpl] - CalDAV IO is properly configured.
2018-04-24 19:46:58.636 [INFO ] [b.core.service.AbstractActiveService] - CalDav Loader has been started
2018-04-24 19:46:59.187 [INFO ] [.io.caldav.internal.CalDavLoaderImpl] - reload job scheduled for: sabine
2018-04-24 19:46:59.201 [INFO ] [.io.caldav.internal.CalDavLoaderImpl] - reload job scheduled for: trash
2018-04-24 19:47:02.523 [INFO ] [.core.internal.i18n.I18nProviderImpl] - Time zone set to 'Europe/Amsterdam'.
2018-04-24 19:47:02.542 [INFO ] [.core.internal.i18n.I18nProviderImpl] - Location set to '52.3xxxxxxxxxxx,4.5xxxxxxxxxxxxxx'.
2018-04-24 19:47:02.551 [INFO ] [.core.internal.i18n.I18nProviderImpl] - Locale set to 'nl_NL'.
2018-04-24 19:47:32.344 [DEBUG] [org.jline                           ] - Error creating JNA based terminal: com/sun/jna/Platform
java.lang.NoClassDefFoundError: com/sun/jna/Platform
        at org.jline.terminal.impl.jna.JnaNativePty.current(JnaNativePty.java:40) ~[14:org.jline:3.6.0]
        at org.jline.terminal.impl.jna.JnaSupportImpl.current(JnaSupportImpl.java:16) ~[14:org.jline:3.6.0]
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:320) [14:org.jline:3.6.0]
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:222) [14:org.jline:3.6.0]
        at org.apache.karaf.shell.impl.console.osgi.LocalConsoleManager.start(LocalConsoleManager.java:65) [12:org.apache.karaf.shell.core:4.1.5]
        at org.apache.karaf.shell.impl.console.osgi.Activator.start(Activator.java:114) [12:org.apache.karaf.shell.core:4.1.5]
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779) [?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1) [?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772) [?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729) [?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:933) [?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309) [?:?]
        at org.eclipse.osgi.container.Module.doStart(Module.java:581) [?:?]
        at org.eclipse.osgi.container.Module.start(Module.java:449) [?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1634) [?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1614) [?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1585) [?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1528) [?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) [?:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [?:?]
Caused by: java.lang.ClassNotFoundException: com.sun.jna.Platform cannot be found by org.jline_3.6.0
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:484) ~[?:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395) ~[?:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387) ~[?:?]
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:?]
        ... 22 more
2018-04-24 19:47:32.966 [WARN ] [org.jline                           ] - Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
2018-04-24 19:47:35.841 [DEBUG] [org.jline                           ] - BundleEvent STARTING - org.jline
2018-04-24 19:47:35.869 [DEBUG] [org.jline                           ] - BundleEvent STARTED - org.jline
```

**Comment by BasvanH** [comment]
@wborn I have narrowed it down. I see this issue with the alpine version, not with debian. Even on build `#1264`.

**Comment by wborn** [comment]
This issue seems to be very specific to running openHAB with the Alpine Docker images on armhf/amd64. I'm closing the issue in this tracker since we also have https://github.com/openhab/openhab-docker/issues/170 for this @BasvanH.

I've created a workaround in https://github.com/openhab/openhab-docker/pull/181 so it is possible to start openHAB in server mode. For more details on this see https://github.com/openhab/openhab-docker/issues/170#issuecomment-399739175.
