### ISSUE TITLE
Freebox binding 1.8 not working in openHAB2 beta 1

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#76]
I add the file org.openhab.binding.freebox-1.8.0.jar in the addons sub-directory and define a freebox.cfg file conf/services sub-directory.

When I start OH2 beta 1, I get this error:

12:57:11.146 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/home/pi/openhab/addons/org.openhab.binding.freebox-1.8.0.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.freebox [166]
  Unresolved requirement: Import-Package: org.openhab.core.binding

        at org.eclipse.osgi.container.Module.start(Module.java:434)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:393)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1245)[8:org.apache.felix.fileinstall:3.5.0]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1217)[8:org.apache.felix.fileinstall:3.5.0]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:509)[8:org.apache.felix.fileinstall:3.5.0]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:358)[8:org.apache.felix.fileinstall:3.5.0]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:310)[8:org.apache.felix.fileinstall:3.5.0]

openhab> bundle:diag 166
openHAB Freebox Binding (166)
-----------------------------
Status: Installed
Unsatisfied Requirements:
osgi.wiring.package; filter:="(osgi.wiring.package=org.openhab.core.binding)"
osgi.wiring.package; filter:="(osgi.wiring.package=org.openhab.core.events)"
osgi.wiring.package; filter:="(osgi.wiring.package=org.openhab.core.items)"
osgi.wiring.package; filter:="(osgi.wiring.package=org.openhab.core.library.items)"
osgi.wiring.package; filter:="(osgi.wiring.package=org.openhab.core.library.types)"
osgi.wiring.package; filter:="(osgi.wiring.package=org.openhab.core.types)"
osgi.wiring.package; filter:="(osgi.wiring.package=org.openhab.model.item.binding)"

**Comment by kaikreuzer** [comment]
Freebox 1.8 is not supported since a 2.0 version is already available. Please wait for the next build which includes https://github.com/openhab/openhab2-addons/issues/626 and try again. Thanks!

**Comment by lolodomo** [comment]
I would like to use the 1.8 version of the binding because the 2.0 version of the binding suppressed interesting features I added and used.
So I will test again 2.0 version to give a feedback but I need the 1.8 version until 2.0 is enhanced with missing features.

**Comment by lolodomo** [comment]
Does the presence of the 2.0 binding (even not installed) prevent the usage of the same 1.8 binding ?
If it is, is there a workaround to use the 1.8 binding ?

Or is it just a bug in the compatibility layer that could be addressed ?
Or shall we fix something in the 1.8 version to be compatible with OH2 ?

**Comment by kaikreuzer** [comment]
> Or shall we fiix something in the 1.8 version to be compatible with OH2 ?

No, we should spend all effort on making the 2.0 version the one you want to use.
