### ISSUE TITLE
Mios binding 1.8 not working in openHAB2

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#81]
After putting the mios 1.8 jar file in the addons sub-directory and defining a mios.cfg file, here are the errors when starting openHAB2:

```

15:57:11.362 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/home/pi/openhab/addons/org.openhab.binding.mios-1.8.0.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.mios [171]
  Unresolved requirement: Import-Package: org.codehaus.jackson

        at org.eclipse.osgi.container.Module.start(Module.java:434)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:393)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1245)[8:org.apache.felix.fileinstall:3.5.0]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1217)[8:org.apache.felix.fileinstall:3.5.0]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1207)[8:org.apache.felix.fileinstall:3.5.0]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:504)[8:org.apache.felix.fileinstall:3.5.0]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:358)[8:org.apache.felix.fileinstall:3.5.0]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:310)[8:org.apache.felix.fileinstall:3.5.0]
15:57:12.160 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/home/pi/openhab/addons/org.openhab.binding.mios-1.8.0.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.mios [171]
  Unresolved requirement: Import-Package: org.codehaus.jackson

        at org.eclipse.osgi.container.Module.start(Module.java:434)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:393)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1245)[8:org.apache.felix.fileinstall:3.5.0]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1217)[8:org.apache.felix.fileinstall:3.5.0]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:509)[8:org.apache.felix.fileinstall:3.5.0]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:358)[8:org.apache.felix.fileinstall:3.5.0]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:310)[8:org.apache.felix.fileinstall:3.5.0]
```

**Comment by kaikreuzer** [comment]
These problems should be fixed with the latest build: https://openhab.ci.cloudbees.com/job/openHAB-Distribution/88/

**Comment by kaikreuzer** [comment]
Note: Please install the compat layer beforehand, see step 2 in https://github.com/openhab/openhab-distro/blob/master/docs/sources/features/compatibilitylayer.md#how-to-use-openhab-1x-add-ons-that-are-not-part-of-the-distribution
