### ISSUE TITLE
NPE when launching demo app

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#908]
When launching the demo app in the IDE, I see this error in the console:
```
23:12:34.657 [openhab.addons)] ERROR L.org.apache.felix.configadmin:? - Unexpected problem delivering configuration event to [org.osgi.service.cm.ConfigurationListener, id=47, bundle=19/reference:file:/Users/kai/.m2/repository/org/apache/felix/org.apache.felix.log/1.2.0/org.apache.felix.log-1.2.0.jar]
java.lang.reflect.UndeclaredThrowableException: null
	at com.sun.proxy.$Proxy4.configurationEvent(Unknown Source)
	at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.sendEvent(ConfigurationManager.java:1685)
	at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.run(ConfigurationManager.java:1637)
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:138)
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:105)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.felix.log.ConfigurationListenerImpl$CLProxy.getProperties(ConfigurationListenerImpl.java:161)
	at org.apache.felix.log.ConfigurationListenerImpl$CLProxy.access$500(ConfigurationListenerImpl.java:67)
	at org.apache.felix.log.ConfigurationListenerImpl$CLProxy$1.invoke(ConfigurationListenerImpl.java:147)
	... 6 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.apache.felix.cm.impl.ConfigurationAdapter.getProcessedProperties(ConfigurationAdapter.java:293)
	... 13 common frames omitted
23:12:34.657 [openhab.addons)] ERROR L.org.apache.felix.configadmin:? - Unexpected problem delivering configuration event to [org.osgi.service.cm.ConfigurationListener, id=47, bundle=19/reference:file:/Users/kai/.m2/repository/org/apache/felix/org.apache.felix.log/1.2.0/org.apache.felix.log-1.2.0.jar]
java.lang.reflect.UndeclaredThrowableException: null
	at com.sun.proxy.$Proxy4.configurationEvent(Unknown Source)
	at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.sendEvent(ConfigurationManager.java:1685)
	at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.run(ConfigurationManager.java:1637)
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:138)
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:105)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.felix.log.ConfigurationListenerImpl$CLProxy.getProperties(ConfigurationListenerImpl.java:161)
	at org.apache.felix.log.ConfigurationListenerImpl$CLProxy.access$500(ConfigurationListenerImpl.java:67)
	at org.apache.felix.log.ConfigurationListenerImpl$CLProxy$1.invoke(ConfigurationListenerImpl.java:147)
	... 6 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.apache.felix.cm.impl.ConfigurationAdapter.getProcessedProperties(ConfigurationAdapter.java:293)
	... 13 common frames omitted
```
@maggu2810 Did you come across this already? Any idea how it can be prevented?

**Comment by maggu2810** [comment]
> @maggu2810 Did you come across this already?

No, did not see it ever with my demo app.

What has been the cause of the metatype error?
There seems to be some significant differences between our setups.

**Comment by kaikreuzer** [comment]
> There seems to be some significant differences between our setups.

Hm, as I said, I copied it 1:1 from your repo and am not aware of any changes (apart from the parent reference pom) to it...

**Comment by wborn** [comment]
Is this still an issue @kaikreuzer?

**Comment by kaikreuzer** [comment]
No, haven't seen it anymore, so let's close it.
