### ISSUE TITLE
Tinkerforge binding 1.8.0 not working in OH2 Beta 1

### ISSUE THREAD

**Issue by sihui62** [openhab/openhab-distro#92]
Official OH2 Beta 1, Tinkerforge binding 1.8.0 (included in distro), platform Raspberry Pi 2, operating system Raspbian Jessie:
At the OH2 starting console I get the following error message:
```
pi@raspberrypi2 ~ $ sudo /opt/openhab/start_debug.sh
Launching the openHAB runtime...
Listening for transport dt_socket at address: 5005

-------------------------------------------------------------------------
Welcome to openHAB 2.0.0.b1
-------------------------------------------------------------------------

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown openHAB.

openhab> Exception in thread "Callback-Processor" java.lang.NullPointerException
        at org.openhab.binding.tinkerforge.internal.model.impl.MBrickdImpl$DisconnectedListener.disconnected(MBrickdImpl.java:807)
        at com.tinkerforge.IPConnection.callDisconnectedListeners(IPConnection.java:152)
        at com.tinkerforge.CallbackThread.dispatchMeta(IPConnectionBase.java:176)
        at com.tinkerforge.CallbackThread.run(IPConnectionBase.java:280) 
```

openhab.log shows:
```
2016-01-17 08:46:05.505 [INFO ] [b.core.service.AbstractActiveService] - Tinkerforge Refresh Service has been started
2016-01-17 08:46:05.589 [ERROR] [orge.internal.model.impl.MBrickdImpl] - Tinkerforge Error: Tinkerforge "not connected" occurred : null
2016-01-17 08:46:05.788 [ERROR] [.internal.model.MIndustrialQuadRelay] - Tinkerforge Error: Tinkerforge "not connected" occurred : null
2016-01-17 08:47:05.511 [INFO ] [b.core.service.AbstractActiveService] - Tinkerforge Refresh Service has been shut down
2016-01-17 09:00:00.127 [WARN ] [org.apache.karaf.services.eventadmin] - EventAdmin: Exception during event dispatch [org.osgi.service.event.Event [topic=openhab/command/Licht_UG_Fountain] | {org.osgi.service.event.EventHandler, org.osgi.service.cm.ManagedService}={event.topics=openhab/command/*, service.pid=org.openhab.tinkerforge, component.name=org.openhab.binding.tinkerforge.binding, component.id=0, service.id=257, service.bundleid=164, service.scope=bundle} | Bundle(org.openhab.binding.tinkerforge_1.8.0 [164])]
java.lang.NullPointerException
    at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.internalReceiveCommand(TinkerforgeBinding.java:797)[164:org.openhab.binding.tinkerforge:1.8.0]
    at org.openhab.core.binding.AbstractBinding.receiveCommand(AbstractBinding.java:97)[150:org.openhab.core.compat1x:2.0.0.b1]
    at org.openhab.core.events.AbstractEventSubscriber.handleEvent(AbstractEventSubscriber.java:42)[150:org.openhab.core.compat1x:2.0.0.b1]
    at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:415)[3:org.apache.karaf.services.eventadmin:4.0.3]
    at org.apache.felix.eventadmin.impl.tasks.HandlerTask.runWithoutBlacklistTiming(HandlerTask.java:102)[3:org.apache.karaf.services.eventadmin:4.0.3]
    at org.apache.felix.eventadmin.impl.tasks.SyncDeliverTasks.execute(SyncDeliverTasks.java:104)[3:org.apache.karaf.services.eventadmin:4.0.3]
    at org.apache.felix.eventadmin.impl.tasks.AsyncDeliverTasks$TaskExecuter.run(AsyncDeliverTasks.java:163)[3:org.apache.karaf.services.eventadmin:4.0.3]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0]
    at java.lang.Thread.run(Thread.java:744)[:1.8.0] 
```

**Comment by kaikreuzer** [comment]
Could you please report it here? https://github.com/openhab/openhab/issues

**Comment by sihui62** [comment]
Done
