### ISSUE TITLE
ZWave and ZigBee bindings are not currently usable

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab-distro#930]
Currently these two bindings do not work with the current development environment as they don't appear in the bnd.app list of repos.

Please see here for more information -:

https://community.openhab.org/t/problems-with-latest-ide-install/76859

It would really be appreciated if this can be resolved quickly so we can continue to develop these bindings..

**Comment by openhab-5iver** [comment]
Adding org.openhab.binding.zigbee and org.openhab.binding.zigbee.ember to the run requirements gives this...
```
Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=org.openhab.binding.zigbee.ember)
          ⇒ [org.openhab.binding.zigbee.ember version=2.5.0.201907070818]
              ⇒ osgi.wiring.package: (&(osgi.wiring.package=org.openhab.binding.zigbee.handler))
                  ⇒ [org.openhab.binding.zigbee version=2.5.0.201907070818]
                      ⇒ osgi.wiring.package: (&(osgi.wiring.package=com.zsmartsystems.zigbee)(&(version>=1.1.0)(!(version>=2.0.0))))
    [org.openhab.binding.zigbee.ember version=2.5.0.201907070818]
      ⇒ osgi.wiring.package: (&(osgi.wiring.package=com.zsmartsystems.zigbee)(&(version>=1.1.0)(!(version>=2.0.0))))
    [org.openhab.binding.smartmeter version=2.5.0.201907070817]
      ⇒ osgi.wiring.package: (&(osgi.wiring.package=io.reactivex)(&(version>=2.2.0)(!(version>=3.0.0))))
    [net.minidev.accessors-smart version=1.2.0]
      ⇒ osgi.wiring.package: (&(osgi.wiring.package=org.objectweb.asm)(&(version>=5.0.0)(!(version>=6.0.0))))
    [org.apache.aries.jpa.container version=2.7.0]
      ⇒ osgi.service: (objectClass=javax.persistence.spi.PersistenceProvider)
    [org.openhab.transform.bin2json version=2.5.0.201907070818]
      ⇒ osgi.wiring.package: (&(osgi.wiring.package=com.igormaznitsa.jbbp)(&(version>=1.4.0)(!(version>=2.0.0))))
    [org.openhab.core.test version=2.5.0.201907071050]
      ⇒ osgi.wiring.package: (&(osgi.wiring.package=org.junit))
    [org.openhab.transform.jinja version=2.5.0.201907070818]
      ⇒ osgi.wiring.package: (&(osgi.wiring.package=com.hubspot.jinjava)(&(version>=2.5.0)(!(version>=3.0.0))))
    [org.openhab.binding.harmonyhub version=2.5.0.201907070818]
      ⇒ osgi.wiring.package: (&(osgi.wiring.package=com.digitaldan.harmony)(&(version>=1.1.0)(!(version>=2.0.0))))
```
There is also an error in Problems...
```
Description	Resource	Path	Location	Type
Failed to read artifact descriptor for org.openhab.addons.bom:org.openhab.addons.bom.zigbee:pom:2.5.0-SNAPSHOT

org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.openhab.addons.bom:org.openhab.addons.bom.zigbee:pom:2.5.0-SNAPSHOT
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:323)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:192)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:539)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:522)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:411)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:365)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:353)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:256)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:282)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:169)
	at org.apache.maven.project.DefaultProjectBuilder.resolveDependencies(DefaultProjectBuilder.java:212)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:185)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:116)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.readMavenProject(MavenImpl.java:628)
	at org.eclipse.m2e.core.internal.project.registry.DefaultMavenDependencyResolver.resolveProjectDependencies(DefaultMavenDependencyResolver.java:63)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refreshPhase2(ProjectRegistryManager.java:525)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.lambda$1(ProjectRegistryManager.java:489)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:488)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:349)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:296)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.getProjectFacade(MavenBuilder.java:155)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:90)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:87)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:201)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.maven.model.resolution.UnresolvableModelException: Failure to find org.openhab.addons.bundles:org.openhab.addons.zigbee.reactor:pom:2.5.0-20190516.035420-7 in https://openhab.jfrog.io/openhab/libs-snapshot was cached in the local repository, resolution will not be reattempted until the update interval of openhab-artifactory-snapshot has elapsed or updates are forced
	at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:178)
	at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:224)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1052)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:830)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:332)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:314)
	... 40 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find org.openhab.addons.bundles:org.openhab.addons.zigbee.reactor:pom:2.5.0-20190516.035420-7 in https://openhab.jfrog.io/openhab/libs-snapshot was cached in the local repository, resolution will not be reattempted until the update interval of openhab-artifactory-snapshot has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:422)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:224)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:201)
	at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:174)
	... 45 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find org.openhab.addons.bundles:org.openhab.addons.zigbee.reactor:pom:2.5.0-20190516.035420-7 in https://openhab.jfrog.io/openhab/libs-snapshot was cached in the local repository, resolution will not be reattempted until the update interval of openhab-artifactory-snapshot has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:233)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:208)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:563)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:481)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:399)
	... 48 more
	pom.xml	/org.openhab.demo.app	line 1	Maven Dependency Problem
```

**Comment by kaikreuzer** [comment]
@cdjackson The Z-Wave binding seems to work now, so I assume we can reduce this issue to Zigbee resolution problems?

**Comment by cdjackson** [comment]
I have finally managed to get the ZWave binding to run although it takes a long time now for the debug session to start.

ZigBee is however still not working.

**Comment by kaikreuzer** [comment]
What is the problem with Zigbee? Still the same problem as given in https://github.com/openhab/openhab-distro/issues/930#issuecomment-509008898?
I currently cannot test myself as I have a very slow Internet connection and m2e takes forever trying to resolve any kind of dependency... 😠

**Comment by cdjackson** [comment]
Yes, it looks similar as the error above, but not exactly the same dependencies.

```
Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=org.openhab.binding.zigbee)
          ⇒ [org.openhab.binding.zigbee version=2.5.0.201907131520]
              ⇒ osgi.wiring.package: (&(osgi.wiring.package=com.zsmartsystems.zigbee)(&(version>=1.1.0)(!(version>=2.0.0))))
    [net.minidev.accessors-smart version=1.2.0]
      ⇒ osgi.wiring.package: (&(osgi.wiring.package=org.objectweb.asm)(&(version>=5.0.0)(!(version>=6.0.0))))
    [org.openhab.transform.bin2json version=2.5.0.201907130429]
      ⇒ osgi.wiring.package: (&(osgi.wiring.package=com.igormaznitsa.jbbp)(&(version>=1.4.0)(!(version>=2.0.0))))
    [org.openhab.core.test version=2.5.0.201907130302]
      ⇒ osgi.wiring.package: (&(osgi.wiring.package=org.junit))
    [org.openhab.binding.smartmeter version=2.5.0.201907130423]
      ⇒ osgi.wiring.package: (&(osgi.wiring.package=io.reactivex)(&(version>=2.2.0)(!(version>=3.0.0))))
    [org.openhab.binding.harmonyhub version=2.5.0.201907130410]
      ⇒ osgi.wiring.package: (&(osgi.wiring.package=com.digitaldan.harmony)(&(version>=1.1.0)(!(version>=2.0.0))))
    [org.openhab.transform.jinja version=2.5.0.201907130430]
      ⇒ osgi.wiring.package: (&(osgi.wiring.package=com.hubspot.jinjava)(&(version>=2.5.0)(!(version>=3.0.0))))
    [org.apache.aries.jpa.container version=2.7.0]
      ⇒ osgi.service: (objectClass=javax.persistence.spi.PersistenceProvider)
```

I guess if you have poor internet, then you're probably on holiday, so don't stress about it - enjoy your holiday :)

**Comment by J-N-K** [comment]
I have seen exactly the same error when trying to resolve Allplay. Allplay uses bundles from the recently added osgiify-repo and my guess is that this repo is not available for the bnd resolver, this could also be true for the zigbee-bundles. Maybe a missing index or something like that. Didn’t have time to investigate that.

**Comment by maggu2810** [comment]
The current demo application contains ALL bundles of the Add-ons repository as dependencies.
That way, you will be able to use every Add-on regardless if it is part of your IDE setup or not.
How has this been managed in PDE (I don't remember).
If all Add-ons have been part of the target platform before, I assume the same data (WRT JAR files) have been downloaded before, too.
Currently Maven downloads all pom files sequentially and not parallel. So it takes a long time until it downloads all Add-ons (also if the Add-ons are part of the IDE, it needs to check which snapshot version is newer.

The initial build of the IDE doesn't seem too clever to me. If you look at the Progress view it seems that the bindings are rebuild multiple time because a dependent project is build.
Shouldn't a dependency tree build first and then the projects build in a correct order that does not need multiple rebuilds?

Perhaps I can try to have a look at the ZigBee binding some time. But I can't promise.

**Comment by kaikreuzer** [comment]
@maggu2810: The resolution of the add-ons is not the problem here, it is the resolution of their dependencies, see @J-N-K's comment.
This seems to affect every add-on, which has external dependencies. For PDE, this was no problem, because we had those add-ons embed their dependencies within the bundle.
For bnd, we will probably need some further bom/index. Do you have any advice, how those dependencies should be best made available here?

**Comment by maggu2810** [comment]
My comment has been also about the general usage. I copied the comment already to the IDE setup.

It depends on the decision which dependencies are "provided" ones and which are really binding specific.
The scope provided for dependencies declares that a dependency is needed for compilation only. So, it is not transitive and also not available at runtime.
If the zigbee binding uses declares the dependency `com.zsmartsystems.zigbee` as provided and the demo app depends on the zigbee binding, the demo app DOES NOT depend on `com.zsmartsystems.zigbee`. It does not know about. It will "consume" the build product of `com.zsmartsystems.zigbee` and so no dependency that is marked as "necessary for build only".

So, we use the dependencies in `org.openhab.core.bom.compile` as "provided" ones, as we are using this ones (in a perfect world only API bundles) for compilation only.
We use the dependencies in `org.openhab.core.bom.runtime` for "runtime" ones. So, dependencies necessary at runtime but not at compile time.

We could provide a compile and runtime collection for the addons similar as for the core one that contains additional dependencies. This way you could mainline the addons dependencies.
But if we consider additional dependencies of addons as addon specific, the addon itself should use the Maven scope correctly and the usage should work (theoretically) out of the box.

**Comment by maggu2810** [comment]
Long story short:

Change from

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.openhab.addons.bundles</groupId>
    <artifactId>org.openhab.addons.zigbee.reactor</artifactId>
    <version>2.5.0-SNAPSHOT</version>
  </parent>

  <artifactId>org.openhab.binding.zigbee</artifactId>

  <name>openHAB Add-ons :: Bundles :: ZigBee Binding</name>

  <dependencies>
    <dependency>
      <groupId>com.zsmartsystems.zigbee</groupId>
      <artifactId>com.zsmartsystems.zigbee</artifactId>
      <version>1.1.6</version>
    </dependency>
  </dependencies>

</project>
```

to

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.openhab.addons.bundles</groupId>
    <artifactId>org.openhab.addons.zigbee.reactor</artifactId>
    <version>2.5.0-SNAPSHOT</version>
  </parent>

  <artifactId>org.openhab.binding.zigbee</artifactId>

  <name>openHAB Add-ons :: Bundles :: ZigBee Binding</name>

  <dependencies>
    <dependency>
      <groupId>com.zsmartsystems.zigbee</groupId>
      <artifactId>com.zsmartsystems.zigbee</artifactId>
      <version>1.1.6</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>

</project>
```

**Comment by kaikreuzer** [comment]
Many thanks for your (always) very detailed and helpful answer! Makes a lot of sense and I wasn't aware that the Zigbee binding actually used the wrong scope for those dependencies.

I have created https://github.com/openhab/org.openhab.binding.zigbee/pull/461 as a fix and it works for me! 🎉

**Comment by cdjackson** [comment]
Thanks both for looking into this. I'll give it a check tonight.
