### ISSUE TITLE
Snapshot 1650: Error downloading javax/activation/activation/1.1.1/activation-1.1.1.jar

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#950]
Error at the first startup of the snapshot 1650:
```
org.apache.karaf.features.internal.util.MultiException: Error:
        Error downloading wrap:file:/home/pi/openhab/userdata/tmp/kar/openhab-addons-2.5.0-SNAPSHOT-1650/javax/activation/activation/1.1.1/activation-1.1.1.jar$Bundle-Name=Javax%20Activation&Bundle-SymbolicName=javax.activation.activation&Bundle-Version=1.1.1
        Error downloading wrap:file:/home/pi/openhab/userdata/tmp/kar/openhab-addons-2.5.0-SNAPSHOT-1650/javax/activation/activation/1.1.1/activation-1.1.1.jar$Bundle-Name=Javax%20Activation&Bundle-SymbolicName=javax.activation.activation&Bundle-Version=1.1.1
        at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.<init>(MavenDownloadManager.java:91)
        at org.apache.karaf.features.internal.download.impl.MavenDownloadManager.createDownloader(MavenDownloadManager.java:72)
        at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:457)
        at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:452)
        at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:224)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:393)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.io.IOException: Error downloading wrap:file:/home/pi/openhab/userdata/tmp/kar/openhab-addons-2.5.0-SNAPSHOT-1650/javax/activation/activation/1.1.1/activation-1.1.1.jar$Bundle-Name=Javax%20Activation&Bundle-SymbolicName=javax.activation.activation&Bundle-Version=1.1.1
                at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:77)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
                ... 3 more
        Caused by: java.io.IOException: Could not download [wrap:file:/home/pi/openhab/userdata/tmp/kar/openhab-addons-2.5.0-SNAPSHOT-1650/javax/activation/activation/1.1.1/activation-1.1.1.jar$Bundle-Name=Javax%20Activation&Bundle-SymbolicName=javax.activation.activation&Bundle-Version=1.1.1]
                at org.apache.karaf.features.internal.download.impl.SimpleDownloadTask.download(SimpleDownloadTask.java:91)
                at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)
                ... 7 more
        Caused by: java.net.MalformedURLException
                at java.net.URL.<init>(URL.java:627)
                at java.net.URL.<init>(URL.java:490)
                at java.net.URL.<init>(URL.java:439)
                at org.apache.karaf.features.internal.download.impl.SimpleDownloadTask.download(SimpleDownloadTask.java:62)
                ... 8 more
        Caused by: java.lang.IllegalStateException
                at org.eclipse.osgi.internal.url.NullURLStreamHandlerService.parseURL(NullURLStreamHandlerService.java:71)
                at org.eclipse.osgi.internal.url.URLStreamHandlerProxy.parseURL(URLStreamHandlerProxy.java:121)
                at java.net.URL.<init>(URL.java:622)
                ... 11 more
        [CIRCULAR REFERENCE:java.io.IOException: Error downloading wrap:file:/home/pi/openhab/userdata/tmp/kar/openhab-addons-2.5.0-SNAPSHOT-1650/javax/activation/activation/1.1.1/activation-1.1.1.jar$Bundle-Name=Javax%20Activation&Bundle-SymbolicName=javax.activation.activation&Bundle-Version=1.1.1]
```

**Comment by lolodomo** [comment]
It did not occur again when I restarted OH. Seems to happen only at first startup when installing everything.
I am using the offline kar file.

**Comment by lolodomo** [comment]
As it does not occur again, I close this issue. Will reopen it in case I see it again.
