### ISSUE TITLE
Exception in opening zip file

### ISSUE THREAD

**Issue by 5iver** [openhab/openhab-distro#974]
Currently happens in S1621, but I've seen this since probably S1566. After clearing the cache, I see these exceptions seven times after startup. After restarting again, the errors do not occur unless the cache is cleared again. It does not appear to affect anything.

```
2019-06-23 02:28:38.172 [INFO ] [javassist] - FrameworkEvent INFO - javassist
java.io.IOException: Exception in opening zip file: /opt/openhab2/userdata/cache/org.eclipse.osgi/25/0/bundleFile
        at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:321) ~[?:?]
        at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.basicOpen(ZipBundleFile.java:93) ~[?:?]
        at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.getZipFile(ZipBundleFile.java:106) ~[?:?]
        at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.checkedOpen(ZipBundleFile.java:65) ~[?:?]
        at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.getEntry(ZipBundleFile.java:240) ~[?:?]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:560) ~[?:?]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:538) ~[?:?]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:525) ~[?:?]
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:328) ~[?:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:368) ~[?:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:446) ~[?:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395) ~[?:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387) ~[?:?]
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:?]
        at org.jvnet.hk2.internal.DelegatingClassLoader.loadClass(DelegatingClassLoader.java:77) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:348) ~[?:?]
        at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:577) ~[?:?]
        at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557) ~[?:?]
        at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230) ~[?:?]
        at java.lang.reflect.WeakCache.get(WeakCache.java:127) ~[?:?]
        at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419) ~[?:?]
        at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719) ~[?:?]
        at org.jvnet.hk2.internal.ProxyUtilities$3.run(ProxyUtilities.java:134) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.jvnet.hk2.internal.ProxyUtilities.secureCreate(ProxyUtilities.java:129) ~[?:?]
        at org.jvnet.hk2.internal.ProxyUtilities.generateProxy(ProxyUtilities.java:208) ~[?:?]
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:1994) ~[?:?]
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114) ~[?:?]
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88) ~[?:?]
        at org.glassfish.jersey.internal.inject.ContextInjectionResolver.resolve(ContextInjectionResolver.java:126) ~[?:?]
        at org.jvnet.hk2.internal.Utilities.justInject(Utilities.java:945) ~[?:?]
        at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:979) ~[?:?]
        at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:969) ~[?:?]
        at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:617) ~[?:?]
        at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:184) ~[?:?]
        at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:350) ~[?:?]
        at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:347) ~[?:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[?:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[?:?]
  at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:255) ~[?:?]
        at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:347) ~[?:?]
        at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:392) ~[?:?]
        at org.glassfish.jersey.servlet.ServletContainer.reload(ServletContainer.java:681) ~[?:?]
        at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.run(ServletContainerBridge.java:54) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) ~[?:?]
Caused by: java.io.FileNotFoundException: /opt/openhab2/userdata/cache/org.eclipse.osgi/25/0/bundleFile (No such file or directory)
        at java.util.zip.ZipFile.open(Native Method) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:169) ~[?:?]
        at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:304) ~[?:?]
        ... 52 more
```

**Comment by wborn** [comment]
If this is still an issue in OH3, please let us know.
