### ISSUE TITLE
Exception while starting SSH server

### ISSUE THREAD

**Issue by weakfl** [openhab/openhab-distro#981]
On `2.5.0~S1710-1` and later builds (confirmed up to `2.5.0~S1712-1` by another user) I get the following exception on startup:

```
2019-10-05 09:08:31.703 [WARN ] [org.apache.karaf.shell.ssh.Activator] - Exception caught while starting SSH server
java.net.UnknownHostException: = 0.0.0.0: Name or service not known
    at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
    at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[?:?]
    at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[?:?]
    at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[?:?]
    at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[?:?]
    at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:?]
    at org.apache.sshd.server.SshServer.start(SshServer.java:318) ~[67:org.apache.sshd.core:1.7.0]
    at org.apache.karaf.shell.ssh.Activator.createAndRunSshServer(Activator.java:120) [63:org.apache.karaf.shell.ssh:4.2.6]
    at org.apache.karaf.shell.ssh.Activator.doStart(Activator.java:109) [63:org.apache.karaf.shell.ssh:4.2.6]
    at org.apache.karaf.util.tracker.BaseActivator.run(BaseActivator.java:292) [63:org.apache.karaf.shell.ssh:4.2.6]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
    at java.lang.Thread.run(Thread.java:748) [?:?]
```

Reverting to `2.5.0~S1709-1` and earlier resolves the issue.

**Comment by wborn** [comment]
I haven't ever seen this on my instances (Ubuntu 18.04, Docker). What distribution and OS do you use?

**Comment by weakfl** [comment]
> @wborn What distribution and OS do you use?

`Raspbian GNU/Linux 9.9 (stretch)`, OH installed through package repository (apt).

**Comment by wborn** [comment]
I can reproduce your issue when I misconfigure the `sshHost` in `userdata/etc/org.apache.karaf.shell.cfg` with:

```
sshHost = = 0.0.0.0
```

Instead of using:

```
sshHost = 0.0.0.0
```

So you might want to double check that file. :wink:

**Comment by weakfl** [comment]
@wborn 

This is the corresponding entry in my `/etc/openhab2/services/runtime.cfg`:
```
org.apache.karaf.shell:sshHost = 0.0.0.0
```

and in `/var/lib/openhab2/etc/org.apache.karaf.shell.cfg`
```
sshHost = 0.0.0.0
```

**Comment by wborn** [comment]
There's also a `userdata/config/org/apache/karaf/shell.config` file with the value which might have gone wrong, it should lines like:

```
$ cat ./userdata/config/org/apache/karaf/shell.config
:org.apache.felix.configadmin.revision:=L"4"
completionMode="GLOBAL"
felix.fileinstall.filename="file:/home/wouter/software/openhab/instance/userdata/etc/org.apache.karaf.shell.cfg"
hostKey="/home/wouter/software/openhab/instance/userdata/etc/host.key"
hostKeyFormat="simple"
service.bundleLocation="?"
service.pid="org.apache.karaf.shell"
sftpEnabled="true"
sshHost="0.0.0.0"
sshIdleTimeout="1800000"
sshPort="8101"
sshRealm="karaf"
```

The configuration in the Karaf console should also show the proper value:

```
openhab> config:list "(service.pid=org.apache.karaf.shell)"                                                                                                
----------------------------------------------------------------
Pid:            org.apache.karaf.shell
BundleLocation: ?
Properties:
   completionMode = GLOBAL
   felix.fileinstall.filename = file:/home/wouter/software/openhab/instance/userdata/etc/org.apache.karaf.shell.cfg
   hostKey = /home/wouter/software/openhab/instance/userdata/etc/host.key
   hostKeyFormat = simple
   service.pid = org.apache.karaf.shell
   sftpEnabled = true
   sshHost = 0.0.0.0
   sshIdleTimeout = 1800000
   sshPort = 8101
   sshRealm = karaf
```

**Comment by weakfl** [comment]
Thanks @wborn, both looking good imho:

`/var/lib/openhab2/config/org/apache/karaf/shell.config`:
```
:org.apache.felix.configadmin.revision:=L"16"
completionMode="GLOBAL"
felix.fileinstall.filename="file:/var/lib/openhab2/etc/org.apache.karaf.shell.cfg"
hostKey="/var/lib/openhab2/etc/host.key"
hostKeyFormat="simple"
service.pid="org.apache.karaf.shell"
sftpEnabled="true"
sshHost="0.0.0.0"
sshIdleTimeout="1800000"
sshPort="8101"
sshRealm="karaf"
```

```
openhab> config:list "(service.pid=org.apache.karaf.shell)"                                                                                                                                                                                                              
----------------------------------------------------------------
Pid:            org.apache.karaf.shell
BundleLocation: mvn:org.apache.karaf.shell/org.apache.karaf.shell.ssh/4.2.6
Properties:
   completionMode = GLOBAL
   felix.fileinstall.filename = file:/var/lib/openhab2/etc/org.apache.karaf.shell.cfg
   hostKey = /var/lib/openhab2/etc/host.key
   hostKeyFormat = simple
   service.pid = org.apache.karaf.shell
   sftpEnabled = true
   sshHost = 0.0.0.0
   sshIdleTimeout = 1800000
   sshPort = 8101
   sshRealm = karaf
```

**However**, this is still on `2.5.0~S1709-1`.
I will update to a recent snapshot later today (mtb is calling now 😉), and will report back checking the various configurations afterwards.

**Comment by wborn** [comment]
I know it has happened before that some of these files get corrupted data after upgrades but there hasn't been any reproduction scenario.

The = symbol in the exception message should shouldn't be there for sure, which suggests a faulty configuration:

```
java.net.UnknownHostException: = 0.0.0.0: Name or service not known
```

**Comment by weakfl** [comment]
> I know it has happened before that some of these files get corrupted data after upgrades but there hasn't been any reproduction scenario

@wborn I've now upgraded to `2.5.0~S1719-1` and sure enough everything is working as expected :/

So I can only guess that your assumption is correct and one of the config files got corrupted somehow.

I'm closing this, thanks a lot for your help!

**Comment by wborn** [comment]
That's a good thing! Eventually the bug :bug: will resurface and we'll be able to troubleshoot/fix it. :wink:
